<?php
// HUSK BEDRIFTSVARIABLER

if (!defined('ABSPATH')) {
    exit;
}

$url_options = get_option('kag_seo_option_name');
$kurs = !empty($url_options['ka_url_rewrite_kurs']) ? $url_options['ka_url_rewrite_kurs'] : 'kurs';
$instruktor = !empty($url_options['ka_url_rewrite_instruktor']) ? $url_options['ka_url_rewrite_instruktor'] : 'instruktor';

// CPT Kurs
register_post_type('ka_course', array(
    'labels' => array(
        'name' => __('KA kurs', 'kursagenten'),
        'singular_name' => __('KA kurs', 'kursagenten'),
        'menu_name' => __('Kurs', 'kursagenten'),
        'all_items' => __('Alle kurs', 'kursagenten'),
        'edit_item' => __('Rediger kurs', 'kursagenten'),
        'view_item' => __('Vis KA kurs', 'kursagenten'),
        'view_items' => __('Vis KA kurs', 'kursagenten'),
        'add_new_item' => __('Legg til KA kurs', 'kursagenten'),
        'add_new' => __('Legg til KA kurs', 'kursagenten'),
        'new_item' => __('Nytt KA kurs', 'kursagenten'),
        'parent_item_colon' => __('Overordnet KA kurs:', 'kursagenten'),
        'search_items' => __('Søk KA kurs', 'kursagenten'),
        'not_found' => __('Ingen KA kurs funnet', 'kursagenten'),
        'not_found_in_trash' => __('Ingen KA kurs funnet i søppelkurven', 'kursagenten'),
        'archives' => __('KA kursliste', 'kursagenten'),
        'attributes' => __('KA kursattributter', 'kursagenten'),
        'featured_image' => __('Hovedbilde', 'kursagenten'),
        'set_featured_image' => __('Velg hovedbilde', 'kursagenten'),
        'remove_featured_image' => __('Fjern', 'kursagenten'),
        'use_featured_image' => __('Bruk bilde', 'kursagenten'),
        'insert_into_item' => __('Sett inn', 'kursagenten'),
        'uploaded_to_this_item' => __('Lastet opp til dette kurset', 'kursagenten'),
        'filter_items_list' => __('Filtrer kursliste', 'kursagenten'),
        'filter_by_date' => __('Filtrer på dato', 'kursagenten'),
        'items_list_navigation' => __('naviger i kurs', 'kursagenten'),
        'items_list' => __('Kursliste', 'kursagenten'),
        'item_published' => __('KA kurs publisert', 'kursagenten'),
        'item_published_privately' => __('KA kurs publisert privat', 'kursagenten'),
        'item_reverted_to_draft' => __('KA kurs gjort om til kladd', 'kursagenten'),
        'item_scheduled' => __('KA kurs planlagt', 'kursagenten'),
        'item_updated' => __('KA kurs oppdatert', 'kursagenten'),
        'item_link' => __('Link', 'kursagenten'),
        'item_link_description' => __('Link til kurs', 'kursagenten'),
    ),
    'public'        => true,
    'has_archive'   => false,
    'show_in_rest'  => true,
    'show_in_admin_bar' => false,
    'show_in_nav_menus' => true,
    'show_in_menu'  => 'kursagenten',
    'menu_icon'     => 'dashicons-welcome-learn-more',
    'supports'      => array('title', 'editor', 'excerpt', 'thumbnail','custom-fields','page-attributes'),
    'taxonomies'    => array('ka_coursecategory', 'ka_course_location'),
    'rewrite'       => array('slug' => $kurs, 'with_front' => false),
    'hierarchical'  => true,
    'parent_item_colon' => __('Hovedkurs:', 'kursagenten'),
    'delete_with_user' => false,
));

// CPT Kursdato
register_post_type('ka_coursedate', array(
    'labels' => array(
        'name' => __('Kursdatoer', 'kursagenten'),
        'singular_name' => __('Kursdato', 'kursagenten'),
        'menu_name' => __('Kursdatoer', 'kursagenten'),
        'all_items' => __('Kursdatoer', 'kursagenten'),
        'edit_item' => __('Rediger kursdato', 'kursagenten'),
        'view_item' => __('Vis kursdato', 'kursagenten'),
        'view_items' => __('Vis kursdato', 'kursagenten'),
        'add_new_item' => __('Legg til kursdato', 'kursagenten'),
        'add_new' => __('Legg til kursdato', 'kursagenten'),
        'new_item' => __('Ny kursdato', 'kursagenten'),
        'search_items' => __('Søk i kursdato', 'kursagenten'),
        'not_found' => __('Ingen kursdatoer funnet', 'kursagenten'),
        'not_found_in_trash' => __('Ingen kursdatoer funnet i søppelkurven', 'kursagenten'),
        'archives' => __('kursdato arkiv', 'kursagenten'),
        'attributes' => __('Kursdato attributter', 'kursagenten'),
        'set_featured_image' => __('Velg hovedbilde', 'kursagenten'),
        'remove_featured_image' => __('Fjern hovedbilde', 'kursagenten'),
        'use_featured_image' => __('Bruk som hovedbilde', 'kursagenten'),
        'insert_into_item' => __('Sett inn i kursdato', 'kursagenten'),
        'uploaded_to_this_item' => __('Lastet opp til kursdato', 'kursagenten'),
        'filter_items_list' => __('Filtrer kursdato liste', 'kursagenten'),
        'filter_by_date' => __('Filtrer kursdato på dato', 'kursagenten'),
        'items_list_navigation' => __('Kursdato listenavigasjon', 'kursagenten'),
        'items_list' => __('Kursdato liste', 'kursagenten'),
        'item_published' => __('Kursdato publisert.', 'kursagenten'),
        'item_published_privately' => __('Kursdato publisert privat.', 'kursagenten'),
        'item_reverted_to_draft' => __('Kursdato gjort om til kladd.', 'kursagenten'),
        'item_scheduled' => __('Kursdato planlagt.', 'kursagenten'),
        'item_updated' => __('Kursdato oppdatert.', 'kursagenten'),
        'item_link' => __('Kursdato link', 'kursagenten'),
        'item_link_description' => __('Link til en kursdato.', 'kursagenten'),
    ),
    'public'            => false,
    'show_ui'           => true,
    'show_in_menu'      => 'edit.php?post_type=ka_course',
    'show_in_admin_bar' => false,
    'show_in_rest'      => true,
    'menu_icon'         => 'dashicons-calendar-alt',
    'supports'          => array('title', 'custom-fields'),
    'taxonomies'        => array('ka_course_location', 'ka_coursecategory'),
    'rewrite'           => false,
    'publicly_queryable'=> false,
    'query_var'         => false,
    'exclude_from_search' => true,
    'delete_with_user'  => false,
));
