module.exports = {
" - side %d av %d": "- strona %d z %d",
"-- Velg side --": "Wybierz stronę",
"– Brukes for feilsøking og oversikt": "– Służy do rozwiązywania problemów i przeglądu",
"– side %1$d av %2$d": "– strona %1$d z %2$d",
"\"Slug\" er den SEO-vennlige versjonen av url-en. Eksempel /kari-norman": "\"Slug\" to SEO-przyjazna wersja URL. Przykład /kari-norman",
"\"Slug\" er den SEO-vennlige versjonen av url-en. Eksempel /mitt-kurs": "\"Slug\" to SEO- przyjazna wersja URL. Przykład /mój kurs",
"\"Slug\" er den SEO-vennlige versjonen av url-en. Eksempel /oslo": "„Slug” to SEO-przyjazna wersja URL. Przykład /oslo",
"* Merk: Denne delen er fortsatt under utvikling.": "* Uwaga: Ta sekcja jest nadal opracowywana.",
"%1$d %2$s valgt": "%1$d %2$s wybrane",
"%1$s har samme slug som %2$s \"%3$s\"": "%1$s ma ten sam ślimak co %2$s \"%3$s\"",
"%d %s valgt": "%d %s wybrane",
"%d dag": "%d dzień",
"%d kurs": "%d kurs",
"← Tilbake til instruktører": "← Powrót do instruktorów",
"← Tilbake til kurskategorier": "← Powrót do kategorii kursów",
"← Tilbake til kurssteder": "← Powrót do lokalizacji kursów",
"+%d flere": "+%d więcej",
"<a href=\"admin.php?page=design\">Kursdesign</a> – Opprett ønskede sider for kurs, kategorier, steder og instruktører via \"Wordpress sider\". Kortkoder legges inn automatisk.": "<a href=\"admin.php?page=design\">Projekt kursu</a> – utwórz strony potrzebne do kursów, kategorii, lokalizacji i instruktorów za pośrednictwem „WordPress stron”. Shortcody są wstawiane automatycznie.",
"<em>Skjul kategorien og alle tilhørende kurs</em> – både kategorien og alle kurs som er tagget med kategorien skjules helt fra kurslisten. Nyttig for interne kategorier som ikke skal være synlige for besøkende.": "<em>Ukryj kategorię i wszystkie powiązane kursy</em> – zarówno kategoria, jak i wszystkie kursy oznaczone kategorią są całkowicie ukryte na liście kursów. Przydatne dla kategorii wewnętrznych, które nie powinny być widoczne dla odwiedzających.",
"<em>Skjul kun kategorien fra filter</em> – kategorien skjules fra filtervalgene, men kurs som er tagget med kategorien vises fortsatt i kurslisten under sine andre kategorier. Nyttig for «brede» tagger som ikke gir mening som filter (f.eks. «Foredrag», «HMS og sikkerhetskurs»).": "<em>Ukryj tylko kategorię z filtra</em> – kategoria jest ukryta w opcjach filtrowania, ale kursy oznaczone kategorią nadal pojawiają się na liście kursów pod innymi kategoriami. Przydatne w przypadku tagów „szerokich”, które nie mają sensu jako filtry (np. „Wykłady”, „HMS i kursy bezpieczeństwa”).",
"<em>Vis</em> – kategorien vises i filteret og kursene vises i listen (standard).": "<em>Pokaż</em> – kategoria pojawia się w filtrze, a kursy pojawiają się na liście (domyślnie).",
"<p><strong>Bruk Kursagenten instruktørprofil i stedet:</strong></p><ol><li>Slett denne instruktøren</li><li>Lagre et kurs i Kursagenten hvor instruktøren er lagt inn</li></ol>": "<p><strong>Zamiast tego użyj profilu instruktora Kursagenten:</strong></p><ol><li>Usuń tego instruktora</li><li>Zapisz kurs w Kursagenten, do którego dodano instruktora</li></ol>",
"<p><strong>Gå tilbake til Kursagenten-data:</strong></p><ol><li>Deaktiver \"Overstyr profil fra Kursagenten\" knappen</li><li>Oppdater instruktørprofilen i Kursagenten</li><li>Profilen oppdateres her. Merk: instruktøren må være knyttet til et kurs for at dataene skal bli hentet over.</li></ol><p>- Bruker du data fra Kursagenten, slipper du å holde dem oppdatert to steder.<br>- En instruktør som er opprettet i Kursagenten med det samme navnet, vil automatisk bli slått sammen med denne instruktøren.</p>": "<p><strong>Wróć do danych Kursagenten:</strong></p><ol><li>Wyłącz przycisk „Zastąp profil z Kursagenten”</li><li> Zaktualizuj profil instruktora w Kursagenten</li><li>Profil został zaktualizowany tutaj. Uwaga: instruktor musi być połączony z kursem, aby dane mogły zostać pobrane.</li></ol><p>- Jeśli korzystasz z danych z Kursagenten, nie musisz ich aktualizować w dwóch miejscach.<br>- Instruktor utworzony w Kursagenten z ta sama nazwa zostanie automatycznie połączona z tym instruktorem.</p>",
"<strong>Advarsel:</strong> Navn og slug på kurssteder kan ikke endres her. Du kan endre navnet under <a href=\"%s\">Synkronisering</a>.": "<strong>Ostrzeżenie:</strong> Tutaj nie można zmienić nazwy i sluga dla lokalizacji kursów. Nazwę można zmienić w sekcji <a href=\"%s\">Synchronizacja</a>.",
"<strong>Alternativt bilde:</strong> Et ekstra bilde som kan brukes på instruktørsiden.": "<strong>Alternatywny obraz:</strong> dodatkowy obraz, który można wykorzystać na stronie instruktora.",
"<strong>Antall per side:</strong> Velg antall kurs som skal vises per side.": "<strong>Liczba na stronie:</strong> Wybierz, ile kursów ma być wyświetlanych na stronie.",
"<strong>Automatisk opprettelse:</strong> Gå til <a href=\"admin.php?page=design#section-systemsider\">Kursdesign → Wordpress sider</a> og klikk på \"Opprett side\" for hver side du trenger. Kortkoden legges inn automatisk.": "<strong>Automatyczne tworzenie:</strong> Przejdź do <a href=\"admin.php?page=design#section-systemsider\">strony projektowania kursu → WordPress</a> i kliknij „Utwórz stronę” dla każdej potrzebnej strony. Krótki kod jest wstawiany automatycznie.",
"<strong>Automatisk opprydding:</strong> Det kjøres også en automatisk nattlig opprydding klokken 03:00 hver natt, så det er ikke alltid nødvendig å kjøre opprydding manuelt. Bruk manuell opprydding hvis du har mange utløpte kursdatoer som vises på nettsiden og ønsker å rydde opp umiddelbart.": "<strong>Automatyczne czyszczenie:</strong> Automatyczne czyszczenie nocne odbywa się również o godzinie 03:00 każdego wieczoru, więc czyszczenie ręczne nie zawsze jest konieczne. Skorzystaj z ręcznego czyszczenia, jeśli masz wiele wygasłych dat kursów wyświetlanych na stronie internetowej i chcesz je natychmiast wyczyścić.",
"<strong>Automatisk synkronisering via webhooks:</strong> Når webhooks er konfigurert, oppdateres kursene automatisk når de endres i Kursagenten. Dette er den anbefalte metoden for løpende oppdateringer.": "<strong>Automatyczna synchronizacja za pomocą webhooków:</strong> po skonfigurowaniu webhooków kursy są aktualizowane automatycznie po ich zmianie w Kursagenten. Jest to zalecana metoda dokonywania bieżących aktualizacji.",
"<strong>Automatisk:</strong> Steder blir automatisk tilordnet til regioner basert på fylke når regioner er aktivert.": "<strong>Automatycznie:</strong> Lokalizacje są automatycznie przypisywane do regionów na podstawie powiatu, gdy regiony są włączone.",
"<strong>Avkrysning før synkronisering:</strong> Når du klikker på \"Hent alle kurs fra Kursagenten\", kan du kryss av for \"Rydd opp i kurs etter synkronisering\". Dette kjører opprydding automatisk etter at synkroniseringen er fullført. <strong>NB:</strong> Opprydding tar 3-5 minutter ekstra.": "<strong>Pole wyboru przed synchronizacją:</strong> Po kliknięciu „Pobierz wszystkie kursy z Kursagenten” możesz zaznaczyć „Wyczyść kursy po synchronizacji”. Spowoduje to automatyczne czyszczenie po zakończeniu synchronizacji. <strong>Uwaga:</strong> sprzątanie zajmuje dodatkowe 3–5 minut.",
"<strong>Bilde:</strong> Et bilde som vises på stedssiden og i lister.": "<strong>Image: Obraz</strong> wyświetlany na stronie lokalizacji i na listach.",
"<strong>Bilde:</strong> Last opp et hovedbilde som vises på taksonomisiden og i lister.": "<strong>Obraz:</strong> Prześlij główny obraz wyświetlany na stronie taksonomii i na listach.",
"<strong>Bilder:</strong> Bruk plassholder-bilder via kortkodene om du mangler bilder.": "<strong>Obrazy:</strong> użyj obrazów zastępczych za pomocą skrótów, jeśli brakuje obrazów.",
"<strong>Bredde:</strong> Velg om du vil bruke temaets standardbredde eller full bredde. Stort sett vil standardbredde fungerer som tiltenkt.": "<strong>Szerokość:</strong> Wybierz, czy chcesz użyć domyślnej szerokości motywu, czy pełnej szerokości. W większości przypadków szerokość domyślna działa zgodnie z przeznaczeniem.",
"<strong>Bruk i kortkoder:</strong> Du kan filtrere kurssteder basert på region i kortkoden <code class=\"copytext\">[kurssteder]</code>:": "<strong>Użyj w shortcodach:</strong> Możesz filtrować lokalizacje kursów według regionu w <code class=\"copytext\">[kurssteder]</code> shortcode:",
"bilde, ikon<br><strong>Standard:</strong> bilde": "obraz, ikona<br><strong>Domyślnie:</strong> obraz",
"bilde, ka-bilde<br><strong>Standard:</strong> bilde": "obraz, ka-bilde<br><strong>Domyślnie:</strong> obraz",
"Bildeform": "Kształt obrazu",
"Bildestr": "Rozmiar obrazu",
"Blokker XML-RPC i .htaccess (Apache)": "Blokuj XML-RPC w .htaccess (Apache)",
"Bokser": "Pudełka",
"Bredde:": "Szerokość:",
"Bruk": "Stosować",
"Bruk \"Resett til standard\" for å tilbakestille regioninndelingen til standardverdiene.": "Użyj opcji „Przywróć domyślne”, aby przywrócić podział regionalny do wartości domyślnych.",
"Bruk bilde": "Użyj obrazu",
"Bruk ekstern lenke på kurstittel": "Użyj zewnętrznego linku w tytule kursu",
"Bruk ekstern lenke på påmeldingsknapp": "Użyj linku zewnętrznego na przycisku rejestracji",
"Bruk kun bakgrunnsfarge": "Używaj tylko koloru tła",
"Bruk kursbilde, og <a href=\"/wp-admin/admin.php?page=design&ka_open=valg-for-bilder%2Cenkeltkurs#valg-for-bilder\">plassholderbilde for kurs</a> om kursbilde mangler": "Użyj obrazu kursu i <a href=\"/wp-admin/admin.php?page=design&ka_open=valg-for-bilder%2Cenkeltkurs#valg-for-bilder\">obrazu zastępczego kursu</a>, jeśli brakuje obrazu kursu",
"Bruk kursbilde, og bakgrunnsfarge om kursbilde mangler": "Użyj obrazu kursu i koloru tła, jeśli brakuje obrazu kursu",
"Bruk parameterne <code>type</code>, <code>start</code> og eventuelt <code>st</code> for å styre hvilke kategorier/steder eller instruktører som skal vises.": "Użyj parametrów <code>type</code>, <code>start</code> i opcjonalnie <code>st</code>, aby kontrolować, które kategorie/lokalizacje lub instruktorzy mają być wyświetlani.",
"Bruk som hovedbilde": "Użyj jako wyróżnionego obrazu",
"Bruk standard (%s)": "Użyj domyślnego (%s)",
"Bruk standard innstilling": "Użyj ustawienia domyślnego",
"Bruk standardvalg": "Użyj domyślnego wyboru",
"Bruk standardvalg for valgt listedesign": "Użyj domyślnego wyboru dla wybranego projektu listy",
"Bruk taksonomibilde, og <a href=\"/wp-admin/admin.php?page=design&ka_open=valg-for-bilder%2Ctaksonomi#valg-for-bilder\">generelt plassholderbilde</a> om bilde mangler": "Użyj obrazu taksonomii i <a href=\"/wp-admin/admin.php?page=design&ka_open=valg-for-bilder%2Ctaksonomi#valg-for-bilder\">ogólnego obrazu zastępczego</a>, jeśli brakuje obrazu",
"Bruk taksonomibilde, og bakgrunnsfarge om bilde mangler": "Użyj obrazu taksonomii i koloru tła, jeśli brakuje obrazu",
"Brukes for å fremheve enkelte bokser i \"Bokser\"-design. Hvis kun «Bakgrunn fremhevede områder» er satt, får begge samme farge.": "Służy do podświetlania niektórych pudełek w projekcie „Pudełka”. Jeśli ustawione jest tylko „Tło dla podświetlonych obszarów”, oba otrzymają ten sam kolor.",
"Byggeblokker for enkeltkurs kommer i en senere oppdatering. Foreløpig kan du bygge innhold med tema/page builder og eksisterende hooks/kortkoder.": "Bloki dla pojedynczych kursów pojawią się w późniejszej aktualizacji. Na razie możesz tworzyć treści za pomocą narzędzia do tworzenia motywów/stron i istniejących hooków/skrótów.",
"Cloudflare blokkerer nedlastingen med bot-verifisering. URL: %s. Løsning: Gå til Cloudflare Dashboard > Security > WAF > Custom Rules og legg til regel som tillater /kursagenten-api/download_plugin, eller deaktiver Bot Fight Mode for denne URL-en.": "Cloudflare blokuje pobieranie poprzez weryfikację bota. Adres URL: %s. Rozwiązanie: Przejdź do Cloudflare Dashboard > Bezpieczeństwo > WAF > Reguły niestandardowe i dodaj regułę zezwalającą na /kursagenten-api/download_plugin lub wyłącz tryb walki z botami dla tego adresu URL.",
"Course Image": "Obraz kursu",
"Dag": "Dzień",
"Dag-/kveldskurs": "Kurs dzienny/wieczorowy",
"Dato": "Data",
"Dato og tittel": "Data i tytuł",
"Deaktiver Gravatar på frontend": "Wyłącz Gravatar na interfejsie",
"Del dette kurset": "Udostępnij ten kurs",
"Denne siden hjelper deg raskt i gang med å sette opp Kursagenten-pluginen fra A til Å. Følg stegene i rekkefølge, og bruk venstremenyen for å hoppe mellom seksjoner.": "Ta strona pomoże Ci szybko rozpocząć konfigurację wtyczki Kursagenten od A do Z. Postępuj zgodnie z instrukcjami w podanej kolejności i użyj menu po lewej stronie, aby przełączać się między sekcjami.",
"Denne visningen bruker den enklere listen med neste tilgjengelige dato og har ikke de samme filtervalgene som \"Vis alle kursdatoer\".": "W tym widoku używana jest prostsza lista z następną dostępną datą i nie ma takich samych opcji filtrowania jak „Pokaż wszystkie daty kursów”.",
"Design": "Projekt",
"Design på taksonomi": "Projekt taksonomii",
"Design:": "Projekt:",
"Design: Lister og grid <span class=\"small\"><a href=\"#lister\">mer info</a></span>": "Projekt listy i siatki <span class=\"small\"><a href=\"#lister\">więcej informacji</a></span>",
"Designet på listene kan endres med attributter i kortkoden. Se <a href=\"#lister\">oversikt</a> for å se hvilke valg du kan gjøre.": "Projekt listy można zmienić za pomocą atrybutów w krótkim kodzie. Zobacz <a href=\"#lister\">przegląd</a> dostępnych opcji.",
"Designmalene viser frem innholdet på forskjellige måter.": "Szablony projektów prezentują treść na różne sposoby.",
"Designmaler": "Szablony projektów",
"Designmaler for kurs": "Szablony projektów kursów",
"Designvalg": "Opcje projektowania",
"Designvariabler": "Zmienne projektowe",
"Desktop:": "Pulpit:",
"Det er for øyeblikket ingen instruktører å vise.": "Aktualnie nie ma instruktorów do wyświetlenia.",
"Det er for øyeblikket ingen kurssteder å vise.": "Obecnie nie ma lokalizacji kursów do wyświetlenia.",
"Det er for øyeblikket ingen relaterte kurs å vise.": "Obecnie nie ma żadnych powiązanych kursów do wyświetlenia.",
"Det er foreløpig ikke mange designmaler tilgjengelig for enkeltkurs. Vi planlegger å utvide med flere designmaler snart.": "Nie ma jeszcze zbyt wielu szablonów projektów dostępnych dla pojedynczych kursów. Wkrótce planujemy dodać więcej szablonów projektów.",
"Det er ikke satt opp dato for nye kurs. Meld din interesse for å få mer informasjon eller å sette deg på venteliste.": "Nie ustalono daty rozpoczęcia nowych kursów. Zarejestruj swoje zainteresowanie, aby uzyskać więcej informacji lub zapisać się na listę oczekujących.",
"Det finnes to måter å rydde opp på:": "Sprzątać można na dwa sposoby:",
"Det gamle stedet blir ikke slettet, men blir ikke lenger synlig på nettsiden.": "Stara lokalizacja nie zostanie usunięta, ale nie będzie już widoczna na stronie.",
"Det opprettes også automatisk en side for betaling når pluginen aktiveres. Denne siden inneholder kode som genererer betalingsboksen og er nødvendig for at betalingsfunksjonaliteten skal fungere. Betalingssiden publiseres automatisk, mens de andre oversiktssidene opprettes som kladd (draft) slik at du kan redigere dem før publisering.": "Strona płatności tworzona jest również automatycznie po aktywacji wtyczki. Ta strona zawiera kod generujący pole płatności i jest wymagany do działania funkcji płatności. Strona płatności jest publikowana automatycznie, natomiast pozostałe strony przeglądu tworzone są jako wersje robocze, dzięki czemu można je edytować przed publikacją.",
"Dette bildet brukes som hovedbilde på instruktørprofilen.": "Ten obraz jest używany jako główny obraz w profilu instruktora.",
"Dette bildet kan brukes som et alternativt bilde på instruktørprofilen.": "Tego obrazu można użyć jako alternatywnego obrazu w profilu instruktora.",
"Dette er den største fontstørrelsen du vil bruke for tekst og overskrifter.": "Jest to największy rozmiar czcionki, jakiego będziesz używać w tekście i nagłówkach.",
"Dette feltet er overskrevet fra Kursagenten": "To pole zostało zastąpione przez Kursagenten",
"Dette feltet viser om bildet er automatisk hentet fra Kursagenten.": "To pole pokazuje, czy obraz został automatycznie pobrany z Kursagenten.",
"Dette legger inn rating i Course schema på kurssidene. Det legger også inn redirect basert på querystrings i eposter fra Kursagenten, til rating-skjema på korrekt kursside.<br><br>": "Spowoduje to dodanie oceny do schematu kursu na stronach kursów. Dodaje także przekierowanie na podstawie ciągów zapytań w wiadomościach e-mail od Kursagenten do formularza oceny na właściwej stronie kursu.<br><br>",
"Dette valget deaktiverer Gravatar på frontend og bruker et lokalt standardbilde i stedet. Dette kan løse problemer med tracking prevention i enkelte nettlesere.<br><br>": "Ta opcja wyłącza Gravatar na interfejsie użytkownika i zamiast tego używa lokalnego obrazu domyślnego. Może to rozwiązać problemy z zapobieganiem śledzeniu w niektórych przeglądarkach.<br><br>",
"Dette valget legger til:<br>1) Clickjacking Protection (X-Frame-Options) i WordPress, styrker security headers.<br>2) Deaktiverer tema- og plugin redigering<br>3) Fjerner WP versjonsnummer<br>4) Deaktiverer XML-RPC i WordPress<br><br>": "Ta opcja dodaje:<br>1) Ochrona przed kliknięciami (opcje X-Frame) w WordPress, wzmacnia nagłówki bezpieczeństwa.<br>2) Wyłącza edycję motywów i wtyczek<br>3) Usuwa numer wersji WP<br>4) Wyłącza XML-RPC w WordPress<br><br>",
"Disse innstillingene fungerer som standardvalg for kortkodene. Du kan også overstyre dem direkte i kortkoden med attributter. Se <a href=\"#lister\">Kortkoder for lister og grid</a> for mer informasjon.": "Te ustawienia działają jako domyślne dla krótkich kodów. Możesz także zastąpić je bezpośrednio w krótkim kodzie za pomocą atrybutów. Więcej informacji znajdziesz w artykule <a href=\"#lister\">Skróty dotyczące list i siatki</a>.",
"Disse innstillingene kan settes både ved redigering av kategorien, via hurtigredigering, og via masseredigering («Kursagenten: Masserediger synlighet») i oversikten.": "Ustawienia te można skonfigurować podczas edycji kategorii, poprzez szybką edycję i edycję zbiorczą („Kursagenten: Widoczność edycji zbiorczej”) w przeglądzie.",
"Disse slugene bruker fallback med prefix.": "Te ślimaki używają rezerwy z prefiksem.",
"Dokumentasjon": "Dokumentacja",
"Dra automenyen til riktig plassering i menystrukturen. Som hovedmenypunkt kan den stå på toppnivå, eller du kan dra den innunder en eksisterende side (f.eks. \"Kurs\") for å bruke den som undermeny.": "Przeciągnij menu automatyczne do właściwej pozycji w strukturze menu. Jako pozycja menu głównego może znajdować się na najwyższym poziomie lub możesz ją przeciągnąć pod istniejącą stronę (np. „Kursy”), aby użyć jej jako podmenu.",
"Dra fylker mellom regionene for å organisere dem etter dine behov.": "Przeciągaj hrabstwa pomiędzy regionami, aby uporządkować je zgodnie ze swoimi potrzebami.",
"Dra fylker mellom regioner for å organisere dem. Merk at en del fylker er utdaterte, men er inkludert for bakover-kompatibilitet. Bruk \"Resett til standard\" for å tilbakestille regioninndelingen til standardverdiene.": "Przeciągnij hrabstwa pomiędzy regionami, aby je uporządkować. Należy pamiętać, że niektóre hrabstwa są przestarzałe, ale uwzględniono je w celu zapewnienia kompatybilności wstecznej. Użyj opcji „Przywróć domyślne”, aby zresetować podział regionalny do wartości domyślnych.",
"Dra menypunktet dit menyen skal vises, for eksempel som undermeny under siden \"Kurs\".": "Przeciągnij pozycję menu tam, gdzie powinno się pojawić menu, na przykład jako podmenu na stronie „Kursy”.",
"Du finner innstillingene for <strong><a href=\"https://kursadmin.kursagenten.no/ProviderInformation\" target=\"_blank\">Tilbyder ID og Tilbyder Guid</a></strong> i Kursagenten under <em>Bedriftsinsformasjon-> Innstillinger</em>, og <strong><a href=\"https://kursadmin.kursagenten.no/IframeSetting\" target=\"_blank\">Tema for kurslister</a></strong> under <em>Embedded / iframe</em><br><br>I Integrasjonsinnstillinger, under fanen <strong><a href=\"https://kursadmin.kursagenten.no/IntegrationSettings\" target=\"_blank\">Webhooks</a></strong>, skal du legge inn %s i feltene CourseCreated og CourseUpdated for å automatisk oppdatere kurs når det blir opprettet eller endret på Kursagenten.": "Ustawienia <strong><a href=\"https://kursadmin.kursagenten.no/ProviderInformation\" target=\"_blank\">Identyfikator dostawcy i GUID dostawcy</a></strong> znajdziesz w Kursagenten w sekcji <em>Informacje o firmie -> Ustawienia</em> i <strong><a href=\"https://kursadmin.kursagenten.no/IframeSetting\" target=\"_blank\">Motyw kursu listy</a></strong> w sekcji <em>Embedded / iframe</em><br><br>W ustawieniach integracji, na karcie <strong><a href=\"https://kursadmin.kursagenten.no/IntegrationSettings\" target=\"_blank\">Webhooks</a></strong> wpisz %s w polach CourseCreated i CourseUpdated, aby automatycznie aktualizować kursy po ich utworzeniu lub zmianie w Kursagenten.",
"Du har flere alternativer:": "Masz kilka opcji:",
"Du har ikke tilgang til denne funksjonen.": "Nie masz dostępu do tej funkcji.",
"Du har ikke tillatelse til å åpne denne siden.": "Nie masz uprawnień, aby otworzyć tę stronę.",
"Du kan bruke blokkene i stedet for kortkoder hvis du bygger sidene med Gutenberg. De samme valgene som beskrives under <a href=\"#lister\">Kortkoder for lister og grid</a> er i stor grad tilgjengelige direkte i blokkinnstillingene.": "Jeśli tworzysz strony za pomocą Gutenberga, możesz używać bloków zamiast krótkich kodów. Te same opcje, które opisano w sekcji <a href=\"#lister\">Skróty dla list i siatki</a> są w dużej mierze dostępne bezpośrednio w ustawieniach bloków.",
"Du kan endre navn på kurssteder som kommer fra Kursagenten. Dette er nyttig hvis du ønsker å bruke kortere eller mer beskrivende navn på nettsiden.": "Możesz zmienić nazwę lokalizacji kursów pochodzących z Kursagenten. Jest to przydatne, jeśli chcesz mieć krótsze lub bardziej opisowe nazwy na stronie internetowej.",
"Du kan endre navn på kurssteder som kommer fra Kursagenten. Dette gjøres via <a href=\"admin.php?page=kursinnstillinger#location-name-mapping\">Synkronisering → Navnendring på kurssteder</a>. Se <a href=\"#stedsnavn-og-regioner\">Stedsnavn og regioner</a> for mer informasjon.": "Możesz zmienić nazwę lokalizacji kursów pochodzących z Kursagenten. Odbywa się to poprzez <a href=\"admin.php?page=kursinnstillinger#location-name-mapping\">Synchronizację → Zmiany nazwy lokalizacji kursu</a>. Więcej informacji znajdziesz w artykule <a href=\"#stedsnavn-og-regioner\">Nazwy lokalizacji i regiony</a>.",
"Du kan fritt endre tittel, slug og innhold på sidene. Det eneste som ikke bør fjernes er kortkoden.": "Możesz dowolnie zmieniać tytuł, ślimak i treść na stronach. Jedyne, czego nie należy usuwać, to krótki kod.",
"Du kan kontrollere hvor kategoriene vises med flere synlighetsinnstillinger:": "Możesz kontrolować, gdzie pojawiają się kategorie, korzystając z kilku ustawień widoczności:",
"Du kan legge inn menypunkter som automatisk generer kurskategorier, kurssteder og instruktører. Mer informasjon i seksjonen <a href=\"#menyer\">Menyer</a>.": "Możesz dodać pozycje menu, które automatycznie generują kategorie kursów, lokalizacje kursów i instruktorów. Więcej informacji w sekcji <a href=\"#menyer\">Menu</a>.",
"Du kan legge til ekstra tekst over eller under kortkoden for introduksjon, SEO-tekst eller annen informasjon.": "Możesz dodać dodatkowy tekst powyżej lub poniżej krótkiego kodu w celu wprowadzenia, tekstu SEO lub innych informacji.",
"Du kan melde deg på kurset nå. Etter påmelding vil du få mer informasjon.": "Już teraz możesz zapisać się na kurs. Po rejestracji otrzymasz więcej informacji.",
"Du kan også konfigurere hvordan kurslistene på taksonomisidene skal vises. Se <a href=\"#section-styre-utseende-på-kurslister\">Styre utseende på kurslister</a> for mer informasjon.": "Możesz także skonfigurować sposób wyświetlania list kursów na stronach taksonomii. Więcej informacji znajdziesz w artykule <a href=\"#section-styre-utseende-på-kurslister\">Kontrola wyglądu listy kursów</a>.",
"Du kan opprette instruktører direkte i WordPress som ikke kommer fra Kursagenten:": "Możesz tworzyć instruktorów bezpośrednio w WordPress, którzy nie pochodzą z Kursagenten:",
"Du kan velge en felles designmal for alle taksonomier, eller aktivere separate designmaler for hver taksonomitype:": "Możesz wybrać wspólny szablon projektu dla wszystkich taksonomii lub włączyć osobne szablony projektów dla każdego typu taksonomii:",
"Du kan velge om du vil bruke et bilde du laster opp selv, eller bruke bildet hentet fra Kursagenten. Velg kilde=ka-bilde hvis du vil bruke bilde fra Kursagenten.": "Możesz wybrać, czy chcesz użyć obrazu, który sam przesłałeś, czy obrazu pobranego z Kursagenten. Wybierz kilde=ka-bilde, jeśli chcesz użyć obrazu z Kursagenten.",
"Du kan velge om du vil bruke hovedbilde, eller laste opp egne ikoner for lister. Velg kilde=ikon hvis du vil bruke disse.": "Możesz wybrać, czy chcesz użyć głównego obrazu, czy przesłać własne ikony do list. Wybierz kilde=ikon, jeśli chcesz ich użyć.",
"Du kan velge å vise fullt navn, fornavn eller etternavn på instruktørsiden og i listen med instruktører. Du må både endre innstillinger i Kursdesign og i Wordpress-siden som viser instruktørene.": "Możesz wybrać wyświetlanie imienia i nazwiska, imienia lub nazwiska na stronie instruktora i na liście instruktorów. Musisz zmienić ustawienia zarówno w projekcie kursu, jak i na stronie WordPress wyświetlającej instruktorów.",
"Du må kjøre en full synkronisering (\"Hent alle kurs fra Kursagenten\") for å ta i bruk navnendringene.": "Aby zastosować zmiany w nazwie, musisz przeprowadzić pełną synchronizację („Pobierz wszystkie kursy z Kursagenten”).",
"Du må legge inn lisensnøkkel før du kan bruke innstillingene.": "Aby móc korzystać z ustawień, należy wprowadzić klucz licencyjny.",
"E-post": "E-mail",
"Egen CSS": "Niestandardowy CSS",
"Egne innstillinger for %s": "Ustawienia niestandardowe dla %s",
"Egne instruktører fungerer på samme måte som instruktører fra Kursagenten, men de vil ikke oppdateres automatisk og kan fritt redigeres uten å aktivere \"overstyr\"-funksjoner.": "Instruktorzy niestandardowi działają w taki sam sposób, jak instruktorzy z Kursagenten, ale nie będą aktualizowani automatycznie i można je dowolnie edytować bez włączania funkcji „zastępowania”.",
"Eksempel": "Przykład",
"Ekstern lenke kan legges inn på kurset i feltet \"Link til påmeldingskjema:\" i Kursagenten. Dette vil åpne en valgfri side.": "Link zewnętrzny do kursu można dodać w polu „Link do formularza rejestracyjnego:” w Kursagenten. Spowoduje to otwarcie wybranej strony.",
"Ekstra innhold": "Dodatkowa zawartość",
"eller": "Lub",
"En feil oppstod under filtreringen.": "Wystąpił błąd podczas filtrowania.",
"En feil oppstod under henting av filter counts": "Wystąpił błąd podczas pobierania liczników filtrów",
"En ukjent feil oppstod under filtreringen.": "Podczas filtrowania wystąpił nieznany błąd.",
"Endre navn på nytt sted": "Zmień nazwę nowej lokalizacji",
"Endre navnet på instruktøren": "Zmień nazwisko instruktora",
"Endre url prefix": "Zmień prefiks adresu URL",
"Endrer sidebredde. Gå til <a href=\"/wp-admin/admin.php?page=design#section-designvariabler\">Designvariabler</a> for å endre maks innholdbredde.": "Zmienia szerokość strony. Przejdź do <a href=\"/wp-admin/admin.php?page=design#section-designvariabler\">Zmienne projektowe</a>, aby zmienić maksymalną szerokość treści.",
"Endring av stedsnavn": "Zmiana nazwy lokalizacji kursu",
"Endringene lagres automatisk når du flytter fylker.": "Zmiany są zapisywane automatycznie po przeniesieniu hrabstw.",
"Endringene under gjelder for alle valgte termer. Felter satt til «Ikke endre» blir hoppet over.": "Poniższe zmiany dotyczą wszystkich wybranych terminów. Pola z ustawioną opcją „Nie zmieniaj” są pomijane.",
"Enkel - Kun tittel og kort beskrivelse": "Proste — tylko tytuł i krótki opis",
"Enkle kort": "Proste karty",
"Epost": "E-mail",
"Ett kort per kurs (neste dato)": "Jedna karta na kurs (następny termin)",
"Ett kort per kurs og lokasjon (neste dato per lokasjon)": "Jedna karta na kurs i lokalizację (następny termin na lokalizację)",
"Etter eventuell kursliste-seksjon på detaljsiden.": "Po dowolnej sekcji listy kursów na stronie szczegółów.",
"Etter hele footer-seksjonen (etter &lt;/article&gt;).": "Po całej sekcji stopki (po &lt;/article&gt;).",
"Etter hele siden": "Po całej stronie",
"Etter hovedinnholdet.": "Po głównej treści.",
"Etter introtekst.": "Po tekście wprowadzającym.",
"Etter lenkene i header-seksjonen.": "Po linkach w sekcji nagłówka.",
"Etter modulen \"Neste kurs\".": "Po module „Następny kurs”.",
"Etter paginering": "Po paginacji",
"Etter påmelding vil du få en e-post med mer informasjon om kurset, og hvordan det skal gjennomføres.": "Po rejestracji otrzymasz e-mail z dodatkowymi informacjami na temat kursu i sposobu jego przeprowadzenia.",
"Etter påmelding vil du få en e-post med mer informasjon om kurset.": "Po rejestracji otrzymasz e-mail z dodatkowymi informacjami na temat kursu.",
"Etter sidekolonne/aside.": "Po pasku bocznym/na boku.",
"f.eks. oslo eller ikke-oslo": "np. Oslo czy nie-Oslo",
"Facebook": "Facebooku",
"Farger:": "Zabarwienie:",
"feks 13px, 15px, 18px<br><strong>Standard</strong>: 13px": "np. 13 pikseli, 15 pikseli, 18 pikseli<br><strong>Domyślne</strong>: 13 pikseli",
"feks 15px, 18px, 26px<br><strong>Standard</strong>: 18px": "np. 15 pikseli, 18 pikseli, 26 pikseli<br><strong>Domyślne</strong>: 18 pikseli",
"feks 4/3, 16/9, 1/1<br><strong>Standard</strong>: 4/3": "np. 4/3, 16/9, 1/1<br><strong>Domyślnie</strong>: 4/3",
"feks h3, h4, h5, p, span, div<br><strong>Standard</strong>: h3": "np. h3, h4, h5, p, span, div<br><strong>Domyślnie</strong>: h3",
"Filter": "Filtr",
"Filterboks:": "Pole filtra:",
"Filterinnstillinger": "Ustawienia filtra",
"Filtre – slik fungerer de": "Filtry – jak działają",
"Filtre i venstre kolonne": "Filtry w lewej kolumnie",
"Filtre over kurslisten": "Filtry nad listą kursów",
"Filtrer kurs": "Filtruj kursy",
"Filtrer kursdato liste": "Filtruj listę dat kursów",
"Filtrer kursdato på dato": "Filtruj daty kursów według daty",
"Filtrer kursliste": "Filtruj listę kursów",
"Filtrer kurssteder basert på region (kun hvis regioner er aktivert). Kan kombineres med vis-parameteren (OR-logikk: viser steder fra regionen ELLER de spesifiserte stedene).": "Filtruj lokalizacje kursów według regionu (tylko jeśli regiony są włączone). Można połączyć z parametrem vis (logika OR: pokazuje lokalizacje z regionu LUB określone lokalizacje).",
"Filtrer på dato": "Filtruj według daty",
"Filtrer på instruktør": "Filtruj według instruktora",
"Filtrer på kurskategori": "Filtruj według kategorii kursu",
"Filtrer på kurssted": "Filtruj według lokalizacji kursu",
"Filtrer stedslisten til kun vise spesifikke steder. Kan bruke stedsnavn eller slug (case-insensitive).": "Filtruj listę lokalizacji, aby wyświetlić tylko określone lokalizacje. Możesz używać nazw lokalizacji lub ślimaków (wielkość liter nie ma znaczenia).",
"Finjuster farger:": "Dostosuj kolory:",
"Finn boksen <strong>\"Kursagenten automenyer\"</strong> i venstre kolonne. Hvis du ikke ser den, sjekk at den er aktivert under \"Skjerminnstillinger\" øverst.": "Znajdź pole <strong>„Kursagenten menu automatyczne”</strong> w lewej kolumnie. Jeśli jej nie widzisz, sprawdź, czy jest włączona w „Opcjach ekranu” u góry.",
"Finn det perfekte kurset for deg og din bedrift": "Znajdź kurs idealny dla siebie i swojej firmy",
"Finner du ikke det du leter etter?": "Nie możesz znaleźć tego, czego szukasz?",
"Firmainformasjon": "Dane firmy",
"Firmanavn": "Nazwa firmy",
"Fjern": "Usunąć",
"Fjern %s": "Usuń %s",
"Fjern bilde": "Usuń obraz",
"Fjern filter": "Usuń filtr",
"Fjern foreldrekategori (flytt til toppnivå)": "Usuń kategorię nadrzędną (przejdź na najwyższy poziom)",
"Fjern hovedbilde": "Usuń wyróżniony obraz",
"Flere instruktører": "Więcej instruktorów",
"Flere kurskategorier": "Więcej kategorii kursów",
"Flere kurssteder": "Więcej lokalizacji kursów",
"Flere valg": "Więcej opcji",
"Font for hovedoverskrifter:": "Czcionka głównych nagłówków:",
"Fontmaks": "Czcionka maks",
"Fontmin": "Czcionka min",
"Footer": "Stopka",
"Footer etter": "Stopka po",
"Footer før": "Stopka wcześniej",
"For \"Kategorier og kurs\": velge om menyen bare skal vise kurs (uten kategorinivå).": "Dla „Kategorie i kursy”: wybierz, czy w menu mają być wyświetlane tylko kursy (bez poziomu kategorii).",
"For de kategoriene som har flere nivåer, er det mulighet til å vise kun toppnivåene, kun underkategoriene, kun underkategorier under gitt foreldreslug, eller alle.": "W przypadku kategorii z wieloma poziomami możesz wyświetlić tylko kategorie najwyższego poziomu, tylko podkategorie, tylko podkategorie w ramach danego ślimaka nadrzędnego lub wszystkie.",
"For flere eksempler på meny-kortkoder og hvordan du kan kombinere dem med andre kortkoder, se seksjonen <a href=\"#kortkoder\">Kortkoder</a> lenger opp på denne siden.": "Więcej przykładów skrótów menu i sposobów łączenia ich z innymi skrótami znajdziesz w sekcji <a href=\"#kortkoder\">Skróty</a> w dalszej części tej strony.",
"For instruktører som kommer fra Kursagenten, kan du overskrive dataene med egne verdier:": "W przypadku instruktorów z Kursagenten możesz zastąpić dane własnymi wartościami:",
"For kurstilbydere med få kurs og 1/ingen kategorier: viser kun en flat liste med hovedkurs uten kategorinivå.": "Dla dostawców kursów z kilkoma kursami i 1/bez kategorii: pokazuje tylko płaską listę kursów głównych bez poziomów kategorii.",
"For å vise oversikter og lister med kurs, kategorier, steder og instruktører, må du opprette vanlige WordPress-sider med kortkoder. Disse sidene bør opprettes fra <a href=\"admin.php?page=design#section-systemsider\">Kursdesign → Wordpress sider</a>. Har du allerede sider du ønsker å bruke, velger du dem fra dropdown-menyen.": "Aby wyświetlić przeglądy i listy kursów, kategorii, lokalizacji i instruktorów, musisz utworzyć regularne strony WordPress z krótkimi kodami. Strony te należy utworzyć z <a href=\"admin.php?page=design#section-systemsider\">Projekt kursu → WordPress stron</a>. Jeśli masz już strony, których chcesz użyć, wybierz je z listy rozwijanej.",
"Foreldrekategori": "Kategoria nadrzędna",
"Foreldrekategori:": "Kategoria nadrzędna:",
"Forhåndsvisning: fant ingen publiserte enkeltkurs å bruke som eksempel.": "Podgląd: nie znaleziono opublikowanych pojedynczych kursów, które można by wykorzystać jako przykład.",
"Forhåndsvisning: ingen kommende kurs funnet.": "Podgląd: nie znaleziono nadchodzących kursów.",
"Forhåndsvisning: ingen kontaktinformasjon registrert for valgt kurs.": "Podgląd: brak danych kontaktowych zarejestrowanych dla wybranego kursu.",
"Forhåndsvisning: ingen kursoversiktsside er konfigurert ennå.": "Podgląd: nie skonfigurowano jeszcze strony przeglądu kursu.",
"Forhåndsvisning: ingen kurstider registrert for valgt kurs.": "Podgląd: dla wybranego kursu nie zarejestrowano żadnych godzin zajęć.",
"Forhåndsvisning: ingen påmeldingslenke for valgt kurs.": "Podgląd: brak linku rejestracyjnego na wybrany kurs.",
"Forhåndsvisning: kurset har ingen beskrivelse fra Kursagenten.": "Podgląd: kurs nie posiada opisu z Kursagenten.",
"fornavn, etternavn<br><strong>Standard</strong>: viser fullt navn": "imię, nazwisko<br><strong>Domyślne</strong>: pokazuje pełne imię i nazwisko",
"Forrige": "Poprzedni",
"Fra A til Å": "Od A do Z",
"Fra Å til A": "Od Z do A",
"Fritekst sted": "Lokalizacja dowolnego tekstu",
"Full bredde": "Pełna szerokość",
"Fullt": "Pełny",
"Fullt navn": "Pełne imię i nazwisko",
"Fyll ut navn og eventuelt slug.": "Wpisz nazwę i opcjonalnie ślimak.",
"Før hele header-seksjonen (før &lt;article&gt;).": "Przed całą sekcją nagłówka (przed &lt;artykułem&gt;).",
"Før hovedinnholdet.": "Przed główną treścią.",
"Før introtekst.": "Przed tekstem wprowadzającym.",
"Før kursliste": "Lista kursów przed",
"Før sidekolonne/aside.": "Przed paskiem bocznym/na bok.",
"Generelt plassholderbilde": "Ogólny obraz zastępczy",
"Gjelder filter som er plassert i venstre kolonne på kurslisten.": "Dotyczy filtrów umieszczonych w lewej kolumnie listy kursów.",
"Gjelder foreldrekategori for alle valgte kurskategorier.": "Stosuje kategorię nadrzędną do wszystkich wybranych kategorii kursów.",
"Grid": "Siatka",
"Gridmobil": "Siatka mobilna",
"Gridtablet": "Tablet sieciowy",
"Gutenberg blokker": "Bloki Gutenberga",
"Gyldige regioner: <code>sørlandet</code>, <code>østlandet</code>, <code>vestlandet</code>, <code>midt-norge</code>, <code>nord-norge</code>": "Prawidłowe regiony: <code>sørlandet</code>, <code>østlandet</code>, <code>vestlandet</code>, <code>midt-norge</code>, <code>nord-norge</code>",
"Gå til <a href=\"admin.php?page=bedriftsinformasjon\">Bedriftsinformasjon</a> og fyll ut grunnleggende firmaopplysninger.": "Przejdź do <a href=\"admin.php?page=bedriftsinformasjon\">Informacje o firmie</a> i podaj podstawowe dane firmy.",
"Gå til <a href=\"admin.php?page=design#design-taksonomi\">Kursdesign → Taksonomisider</a>": "Przejdź do <a href=\"admin.php?page=design#design-taksonomi\">Projekt kursu → Strony taksonomii</a>",
"Gå til <a href=\"admin.php?page=design#section-systemsider\">Wordpress sider</a>. Rediger siden med instruktøroversikten og legg til vis=\"fornavn\" eller vis=\"etternavn\" i kortkoden for å vise kun fornavn eller etternavn. Du kan gå direkte til redigering fra <a href=\"admin.php?page=design#section-systemsider\">Wordpress sider</a>.": "Przejdź do <a href=\"admin.php?page=design#section-systemsider\">WordPress stron</a>. Edytuj stronę z przeglądem instruktora i dodaj vis=\"fornavn\" lub vis=\"ettenavn\" do krótkiego kodu, aby wyświetlić tylko imię lub nazwisko. Możesz przejść bezpośrednio do edycji z <a href=\"admin.php?page=design#section-systemsider\">WordPress stron</a>.",
"Gå til <a href=\"admin.php?page=kursinnstillinger\">Synkronisering</a> i WordPress-administrasjonen.": "Przejdź do <a href=\"admin.php?page=kursinnstillinger\">Synchronizacja</a> w panelu administracyjnym WordPress.",
"Gå til <a href=\"admin.php?page=kursinnstillinger#location-name-mapping\">Synkronisering → Navnendring på kurssteder</a>.": "Przejdź do <a href=\"admin.php?page=kursinnstillinger#location-name-mapping\">Synchronizacja → Zmiany nazwy lokalizacji kursu</a>.",
"Gå til <a href=\"admin.php?page=kursinnstillinger#regions\">Synkronisering → Regioner</a>.": "Przejdź do <a href=\"admin.php?page=kursinnstillinger#regions\">Synchronizacja → Regiony</a>.",
"Gå til <a href=\"edit-tags.php?taxonomy=ka_instructors&post_type=ka_course\">Instruktører</a>-oversikten.": "Przejdź do przeglądu <a href=\"edit-tags.php?taxonomy=ka_instructors&post_type=ka_course\">Instruktorzy</a>.",
"Gå til <strong>Utseende → Menyer</strong> i WordPress.": "Przejdź do <strong>Wygląd → Menu</strong> w WordPress.",
"Gå til oversikten over taksonomiene (f.eks. <a href=\"edit-tags.php?taxonomy=ka_coursecategory&post_type=ka_course\">Kurskategorier</a>, <a href=\"edit-tags.php?taxonomy=ka_course_location&post_type=ka_course\">Kurssteder</a> eller <a href=\"edit-tags.php?taxonomy=ka_instructors&post_type=ka_course\">Instruktører</a>) og klikk på \"Rediger\" på den taksonomien du vil berike. Her kan du legge til:": "Przejdź do przeglądu taksonomii (np. <a href=\"edit-tags.php?taxonomy=ka_coursecategory&post_type=ka_course\">kategorii kursów</a>, <a href=\"edit-tags.php?taxonomy=ka_course_location&post_type=ka_course\">lokalizacji kursów</a> lub <a href=\"edit-tags.php?taxonomy=ka_instructors&post_type=ka_course\">Instruktorzy</a>) i kliknij „Edytuj” przy taksonomii, którą chcesz wzbogacić. Tutaj możesz dodać:",
"Handling": "Działanie",
"Handlinger": "Działania",
"Har du funnet feil eller har du forbedringsforslag? Vi hører gjerne fra deg. Vi jobber for å gjøre Kursagenten bedre for deg.<br>Send en epost rett til inboksen i Trello:": "Znalazłeś błąd lub masz sugestie dotyczące ulepszeń? Chcielibyśmy usłyszeć od ciebie. Pracujemy nad tym, aby Kursagenten był dla Ciebie lepszy.<br>Wyślij e-mail bezpośrednio do skrzynki odbiorczej w Trello:",
"Header etter": "Nagłówek po",
"Header etter seksjon": "Nagłówek po sekcji",
"Header etter tittel": "Nagłówek po tytule",
"Header før": "Nagłówek wcześniej",
"Hele filterområdet i venstre kolonne legges i en avrundet boks. Standard bakgrunn følger temafargen (--ka-box-background).": "Cały obszar filtra w lewej kolumnie jest umieszczony w zaokrąglonej ramce. Domyślne tło jest zgodne z kolorem motywu (--ka-box-background).",
"Helt nederst, etter kurslisten (bunnseksjon).": "Na samym dole, po liście kursów (dolna sekcja).",
"Hent alle kurs fra Kursagenten": "Pobierz wszystkie kursy z Kursagenten",
"Hent kursene": "Pobieraj kursy",
"Henting av kurs fra Kursagenten": "Pobieram kursy z Kursagenten",
"Her finner du innstillinger for synkronisering av kurs fra Kursagenten. <br>- Ved å klikke på \"Hent alle kurs fra Kursagenten\" overfører du alle kursene dine. Merk at det kun er enveis-synkronisering.<br>- Vi anbefaler å <strong>synkronisere kursene automatisk</strong>. Legg inn <a href=\"https://kursadmin.kursagenten.no/IntegrationSettings\" target=\"_blank\">Webhooks</a> i Kursagenten, så blir kurset overført når det blir lagret/opprettet. Se url under.<br>- Du kan også rydde opp i kursene hvis det er utdaterte datoer eller lignende.<br><br>": "Tutaj znajdziesz ustawienia synchronizacji kursów z Kursagenten. <br>- Klikając „Pobierz wszystkie kursy z Kursagenten” przenosisz wszystkie swoje kursy. Pamiętaj, że synchronizacja jest tylko jednokierunkowa.<br>- Zalecamy <strong>automatyczną synchronizację kursów</strong>. Dodaj <a href=\"https://kursadmin.kursagenten.no/IntegrationSettings\" target=\"_blank\">Webhooki</a> w Kursagenten, aby kurs został przeniesiony po zapisaniu/utworzeniu. Zobacz adres URL poniżej.<br>- Możesz także wyczyścić kursy, jeśli są nieaktualne daty lub podobne.<br><br>",
"Her kan du endre navn på kurssteder som kommer fra Kursagenten. Når du endrer navn på et sted, blir også slugs (nettadressen) på kursene som har dette stedet oppdatert.<br><br>1. Nytt sted blir lagret når du klikker på \"Lagre\".<br>2. Stedet blir \"oversatt\" til det nye navnet når kurs blir hentet fra Kursagenten.<br>3. Slugs/nettadresser på kursene som har dette stedet oppdateres umiddelbart.<br>4. Det gamle stedet blir ikke slettet, men blir ikke lenger synlig på nettsiden.<br><br>5. <span style=\"color: #d63638;\"><strong>Viktig:</strong></span> For å ta i bruk navnendringene, kjør en full synk fra Kursagenten ved å klikke på \"Hent alle kurs fra Kursagenten\". Husk også å markere \"Rydd opp i kurs\" før du kjører synken.<br><br>": "Tutaj możesz zmienić nazwy lokalizacji kursów pochodzących z Kursagenten. Gdy zmienisz nazwę lokalizacji, aktualizowane są również ślimaki (adresy URL) kursów w tej lokalizacji.<br><br>1. Nowa lokalizacja zostanie zapisana po kliknięciu „Zapisz”.<br>2. Lokalizacja zostanie „przetłumaczona” na nową nazwę, gdy kursy zostaną pobrane z Kursagenten.<br>3. Informacje/adresy URL kursów w tej lokalizacji są natychmiast aktualizowane.<br>4. Stara lokalizacja nie zostanie usunięta, ale nie będzie już widoczna na stronie.<br><br>5. <span style=\"color: #d63638;\"><strong>Ważne:</strong></span> Aby zastosować zmiany w nazwie, przeprowadź pełną synchronizację z Kursagenten, klikając „Pobierz wszystkie kursy z Kursagenten”. Pamiętaj też, aby przed uruchomieniem synchronizacji zaznaczyć opcję „Wyczyść kursy”.<br><br>",
"Her kan du legge til egendefinert CSS som vil bli lastet inn på alle sider som hører til utvidelsen. Denne CSS-en vil ha høyest prioritet og vil overstyre utvidelsens standard CSS.": "Tutaj możesz dodać własny CSS, który będzie ładowany na wszystkich stronach należących do wtyczki. Ten CSS ma najwyższy priorytet i zastępuje domyślny CSS wtyczki.",
"Her kan du skrive inn informasjon som vil bli brukt ulike steder på nettsiden. Dette inkluderer navn på hovedkontakt (personvernerklæring), samt firmanavn og adresse (kontaktside og bunnfelt).": "Wprowadź informacje, które będą wykorzystywane w różnych miejscach serwisu. Obejmuje to główną nazwę osoby kontaktowej (polityka prywatności), a także nazwę i adres firmy (strona kontaktowa i stopka).",
"Her kan du skrive inn informasjon som vil bli brukt ulike steder på nettsiden. Dette inkluderer navn på hovedkontakt (personvernerklæring), samt firmanavn og adresse (kontaktside og bunnfelt).<br>Du kan også legge inn informasjon om bedriften som kan vises på med kortkode. Se alle kortkoder <a href=\"#kortkoder\">her</a>.": "Wprowadź informacje, które będą wykorzystywane w różnych miejscach serwisu. Obejmuje to główną nazwę osoby kontaktowej (polityka prywatności), a także nazwę i adres firmy (strona kontaktowa i stopka).<br>Możesz także dodać informacje o firmie, które można wyświetlić za pomocą krótkiego kodu. Wszystkie skróty znajdziesz <a href=\"#kortkoder\">tutaj</a>.",
"Her kan du skrive inn kort informasjon om bedriften. Denne teksten kan vises på med kortkode.": "Wprowadź krótkie informacje o firmie. Ten tekst można wyświetlić za pomocą krótkiego kodu.",
"Her kan du skrive inn URL til sosiale profiler. Disse kan bli brukt rundt på nettsiden.": "Wprowadź adresy URL profili społecznościowych. Można ich używać w całej witrynie.",
"Hero - to kolonner": "Bohater - dwie kolumny",
"Hero - toppseksjon med bilde": "Bohater - górna część z obrazem",
"Hooks": "Haczyki",
"Hooks kommer...": "Haki już wkrótce...",
"Hovedbilde som brukes på kategorisiden og i kategorioversikter": "Główny obraz używany na stronie kategorii i w przeglądach kategorii",
"Hovedfarge:": "Kolor podstawowy:",
"Hovedfont:": "Podstawowa czcionka:",
"Hovedinnhold etter": "Główna treść po",
"Hovedinnhold før": "Główna treść wcześniej",
"hovedkategorier, subkategorier, foreldreslug (feks dans eller truck)<br><strong>Standard</strong>: viser alle": "kategorie, podkategorie najwyższego poziomu, ślimak nadrzędny (np. taniec lub ciężarówka) <br><strong>Domyślne</strong>: pokaż wszystko",
"Hovedkontakt": "Główny kontakt",
"Hovedkurs:": "Kurs dla rodziców:",
"Hva Kursagenten legger til (når ingen SEO-utvidelse er aktiv)": "Co dodaje Kursagenten (gdy żadna wtyczka SEO nie jest aktywna)",
"Hva ryddes opp:": "Co jest sprzątane:",
"Hver kategori, hvert sted og hver instruktør får automatisk sin egen side. Disse genereres fra maler som velges i <a href=\"admin.php?page=design\">Kursdesign</a>. Du kan berike disse sidene med ekstra innhold, bilder og tekst ved å redigere taksonomiene.": "Każda kategoria, lokalizacja i instruktor automatycznie otrzymują własną stronę. Są one generowane na podstawie szablonów wybranych w <a href=\"admin.php?page=design\">Projekcie kursu</a>. Możesz wzbogacić te strony o dodatkową treść, obrazy i tekst, edytując taksonomie.",
"Hvert kurs har sin egen side som genereres automatisk basert på valgt designmal. Innholdet hentes fra Kursagenten, inkludert bildet. Du kan legge til eget innhold mellom introtekst og hovedinnhold ved å redigere kurset. Du ser en markering for dette området når du besøker siden som administrator, samt en link for å gå til redigering. Det er også snarvei for å redigere kurset i Kursagenten.  Se etter et blyant-ikon du kan klikke på. Dette åpner kurset i Kursagenten, i en ny fane. Gjør endringene du ønsker der, lagre, og så ser du umiddelbart endringene på nettsiden.": "Każdy kurs posiada własną stronę generowaną automatycznie na podstawie wybranego szablonu projektu. Treść jest pobierana z Kursagenten, łącznie z obrazem. Możesz dodać niestandardową treść pomiędzy tekstem wprowadzającym a treścią główną, edytując kurs. Gdy odwiedzisz stronę jako administrator, zobaczysz znacznik tego obszaru oraz link do edycji. Istnieje również skrót do edycji kursu w Kursagenten. Poszukaj ikony ołówka, którą możesz kliknąć. Spowoduje to otwarcie kursu w Kursagenten w nowej karcie. Tam dokonaj zmian, zapisz, a od razu zobaczysz zmiany na stronie.",
"Hvis du oppretter sider for kurs, kurskategorier, kurssteder og/eller instruktører, vil sidene opprettes som vanlige WordPress-sider. Du kan fritt endre tittel og innhold. En <a href=\"/wp-admin/admin.php?page=ka_documentation#kortkoder\">kortkode</a> legges inn automatisk.</br><strong>Blokker:</strong> Taksonomiene Kurskategorier, Kurssteder og Instruktører er tilgjengelige som egne Gutenberg-blokker i blokkeditoren. Du kan velge å bruke blokkene i stedet for kortkoder hvis du bygger sidene med Gutenberg.": "Jeśli tworzysz strony dla kursów, kategorii kursów, lokalizacji kursów i/lub instruktorów, strony te są tworzone jako zwykłe strony WordPress. Możesz dowolnie zmieniać tytuł i treść. <a href=\"/wp-admin/admin.php?page=ka_documentation#kortkoder\">krótki kod</a> jest wstawiany automatycznie.</br><strong>Bloki:</strong> Taksonomie Kategorie kursów, Lokalizacje kursów i Instruktorzy są dostępne jako osobne bloki Gutenberga w edytorze bloków. Jeśli tworzysz strony za pomocą Gutenberga, możesz zdecydować się na użycie bloków zamiast krótkich kodów.",
"Hvis regioner er aktivert, kan du tilordne hvert kurssted til en region (Sørlandet, Østlandet, Vestlandet, Midt-Norge, Nord-Norge). Dette kan gjøres på to måter:": "Jeśli regiony są włączone, możesz przypisać każdą lokalizację kursu do regionu (Sørlandet, Østlandet, Vestlandet, Midt-Norge, Nord-Norge). Można to zrobić na dwa sposoby:",
"Hvordan fallback fungerer: Når \"Skjul i url-er\" er aktivert, forsøker vi først kort URL uten prefix. Hvis slugen er i konflikt med en side/innlegg eller en annen skjult taksonomi, brukes automatisk prefiks-URL (f.eks. <code>/kurskategori/slug/</code> eller din tilpassede verdi som <code>/kat/slug/</code>). Vanlige WordPress-sider og innlegg får alltid prioritet ved konflikt.": "Jak działa rezerwa: gdy włączona jest opcja „Ukryj w adresach URL”, najpierw próbujemy użyć krótkiego adresu URL bez przedrostka. Jeśli ślimak koliduje ze stroną/postem lub inną ukrytą taksonomią, automatycznie używany jest adres URL z prefiksem (np. <code>/kurskategori/slug/</code> lub Twoja wartość niestandardowa, taka jak <code>/kat/slug/</code>). Regularne strony i posty WordPress zawsze mają pierwszeństwo w przypadku konfliktu.",
"Hvordan legge til innhold": "Jak dodać treść",
"Hvordan opprette sidene": "Jak tworzyć strony",
"Hvorvidt bildet skal være liggende, stående eller kvadratisk.": "Czy obraz powinien być poziomy, pionowy czy kwadratowy.",
"Høyde:": "Wysokość:",
"Høyre kolonne bunn": "Prawa kolumna na dole",
"Høyre kolonne topp": "Prawa kolumna u góry",
"I <a href=\"admin.php?page=design\">Kursdesign</a> kan du velge designmaler og innstillinger for taksonomisider (kategorier, kurssteder og instruktører).": "W <a href=\"admin.php?page=design\">Projekt kursu</a> możesz wybrać szablony projektów i ustawienia stron taksonomii (kategorie, lokalizacje kursów i instruktorzy).",
"I <a href=\"admin.php?page=design#section-enkeltkurs\">Kursdesign → Enkeltkurs</a> velger du designmal for enkeltsider for kurs. Designmalen påvirker hele oppsettet av kursdetaljsiden:": "W <a href=\"admin.php?page=design#section-enkeltkurs\">Projekt kursu → Pojedynczy kurs</a> wybierasz szablon projektu dla pojedynczych stron kursu. Szablon projektu wpływa na cały układ strony szczegółów kursu:",
"I <strong>Link-tekst</strong> (eller tilsvarende felt) limer du inn ønsket <code>[ka-meny]</code>-kortkode, f.eks. <code>[ka-meny type=\"kurskategorier\"]</code>.": "W <strong>Tekst linku</strong> (lub równoważnym polu) wklej żądany krótki kod <code>[ka-meny]</code>, np. <code>[ka-meny type=\"kurskategorier\"]</code>.",
"I URL-feltet skriver du <code>#</code> (slik at menypunktet kan lagres uten faktisk lenke).": "W polu URL wpisz <code>#</code> (aby pozycja menu mogła zostać zapisana bez faktycznego linku).",
"I Wordpress finnes to typer sider: Sider og innlegg. Innlegg tilsvarer blogginnlegg eller annet som har kategorier og tagger. Aktiver for å omdøpe innlegg til \"Artikler\".<br><br>": "W WordPress istnieją dwa typy stron: Strony i posty. Posty odpowiadają postom na blogu lub innej treści z kategoriami i tagami. Włącz zmianę nazwy postów na „Artykuły”.<br><br>",
"Ikke begrens høyde": "Nie ograniczaj wzrostu",
"Ikke endre": "Nie zmieniaj",
"Ikke endre foreldrekategori": "Nie zmieniaj kategorii nadrzędnej",
"Ikke opprettet": "Nie utworzono",
"Ikke tilgang": "Odmowa dostępu",
"Ikoner er tilgjengelige som html med css-klasser. Du kan bruke dem direkte i HTML-kode. Styr størrelse og farge med width, height og background-color på i.ka-icon. Husk å legge til <i>icon-</i> før navnet på ikonet. F.eks. icon-calendar. Eksempel:": "Ikony są dostępne w formacie HTML z klasami CSS. Można ich używać bezpośrednio w kodzie HTML. Kontroluj rozmiar i kolor za pomocą szerokości, wysokości i koloru tła na ikonie i.ka. Pamiętaj, aby dodać <i>icon-</i> przed nazwą ikony. Np. ikona-kalendarz. Przykład:",
"Ikoner:": "Ikony:",
"Inaktiv": "Nieaktywny",
"Informasjon": "Informacja",
"Informasjon om kurssteder": "Informacje o lokalizacjach kursów",
"Ingen alternativer tilgjengelig": "Brak dostępnych opcji",
"Ingen elementer funnet.": "Nie znaleziono żadnych elementów.",
"Ingen filtre er konfigurert.": "Nie skonfigurowano żadnych filtrów.",
"Ingen foreldrekategori (toppnivå)": "Brak kategorii nadrzędnej (najwyższy poziom)",
"Ingen gyldig mapping data": "Brak prawidłowych danych mapowania",
"Ingen instruktører": "Żadnych instruktorów",
"Ingen instruktører funnet": "Nie znaleziono instruktorów",
"Ingen KA kurs funnet": "Nie znaleziono kursów KA",
"Ingen KA kurs funnet i søppelkurven": "Nie znaleziono kursów KA w koszu",
"Ingen kurs funnet. Fjern ett eller flere filtre, eller nullstill alle filtre.": "Nie znaleziono kursów. Usuń jeden lub więcej filtrów albo zresetuj wszystkie filtry.",
"Ingen kurs tilgjengelige for dette filteret": "Brak dostępnych kursów dla tego filtra",
"Ingen kurs tilgjengelige for øyeblikket.": "W tej chwili brak dostępnych kursów.",
"Ingen kurs tilgjengelige med valgte filtre. Nullstill filtre hvis du står fast.": "Brak dostępnych kursów z wybranymi filtrami. Zresetuj filtry, jeśli utkniesz.",
"Ingen kurs tilgjengelige.": "Brak dostępnych kursów.",
"Ingen kursdager tilgjengelig.": "Brak dostępnych dni kursu.",
"Ingen kursdatoer funnet": "Nie znaleziono dat kursów",
"Ingen kursdatoer funnet i søppelkurven": "Nie znaleziono dat kursów w koszu",
"Ingen kursdatoer tilgjengelig for øyeblikket.": "W tej chwili brak dostępnych terminów kursów.",
"Ingen kurskategorier": "Brak kategorii kursów",
"Ingen kurskategorier funnet": "Nie znaleziono kategorii kursów",
"Ingen kurssteder": "Brak lokalizacji kursów",
"Ingen kurssteder funnet": "Nie znaleziono lokalizacji kursów",
"Ingen mapping mottatt eller ugyldig format": "Nie otrzymano mapowania lub nieprawidłowy format",
"Ingen treff med valgte filtre. Prøv et annet søk eller juster filtrene.": "Brak dopasowań do wybranych filtrów. Spróbuj innego wyszukiwania lub dostosuj filtry.",
"Innhold": "Treść",
"Innstillinger": "Ustawienia",
"Innstillinger for kursliste": "Ustawienia listy kursów",
"Innstillinger fra Kursagenten": "Ustawienia z Kursagenten",
"Instagram": "Instagrama",
"Instruktør": "Instruktor",
"Instruktør-tittel": "Tytuł instruktora",
"Instruktør-tittel, kurs tittel/beskrivelse": "Tytuł instruktora, tytuł/opis kursu",
"Instruktør:": "Instruktor:",
"Instruktører har samme synlighetsinnstillinger som kurskategorier (skjul i oversiktslister og i automenyer). Du kan også skjule spesifikke instruktører i kortkoder ved å bruke <code>skjul</code>-parameteren i kortkoden <code>[instruktorer]</code>.": "Instruktorzy mają takie same ustawienia widoczności jak kategorie kursów (ukryj je na listach przeglądowych i w menu automatycznym). Możesz także ukryć określonych instruktorów w krótkich kodach, używając parametru <code>skjul</code> w krótkim kodzie <code>[instruktorer]</code>.",
"Instruktører kan berikes med bilder, kontaktinformasjon og beskrivelser. Du kan også opprette egne instruktører som ikke kommer fra Kursagenten, og overskrive data fra Kursagenten.": "Instruktorzy mogą zostać wzbogaceni o zdjęcia, dane kontaktowe i opisy. Możesz także utworzyć niestandardowych instruktorów, którzy nie pochodzą z Kursagenten i zastąpić dane z Kursagenten.",
"Instruktører liste": "Lista instruktorów",
"Instruktører listenavigasjon": "Nawigacja po liście instruktorów",
"Instruktører:": "Instruktorzy:",
"Instruktørlink": "Link do instruktora",
"Introtekst etter": "Tekst wprowadzający po",
"Introtekst før": "Tekst wprowadzający wcześniej",
"Ja": "Tak",
"ja<br><strong>Standard</strong>: uten skygge": "tak<br><strong>Domyślnie</strong>: brak cienia",
"ja<br><strong>Standard</strong>: viser ikke": "tak<br><strong>Domyślnie</strong>: niewidoczne",
"ja<br><strong>Standard</strong>: vises ikke": "tak<br><strong>Domyślne</strong>: nie wyświetlane",
"KA kurs": "Kurs KA",
"KA kurs gjort om til kladd": "Kurs KA powrócił do wersji roboczej",
"KA kurs oppdatert": "Kurs KA zaktualizowany",
"KA kurs planlagt": "Zaplanowano kurs KA",
"KA kurs publisert": "Kurs KA opublikowany",
"KA kurs publisert privat": "Kurs KA opublikowany prywatnie",
"KA kursattributter": "Atrybuty kursu KA",
"KA kursliste": "Archiwum kursów KA",
"Kan brukes i lister med kurskategorier om du ønsker et annet bilde enn hovedbilde. Profilbilde tilsvarer ikon-bilde i eldre oppsett. Bruk en .png eller .svg bildefil. Du kan laste ned ikoner på feks. https://thenounproject.com/": "Można go używać na listach kategorii kursów, jeśli chcesz mieć inny obraz niż główny obraz. Obraz profilowy odpowiada obrazowi ikony w starszych konfiguracjach. Użyj pliku obrazu .png lub .svg. Ikony możesz pobrać m.in. https://thenounproject.com/",
"Kan brukes på": "Można używać na",
"Kategorier": "Kategorie",
"Kategorier og kurs": "Kategorie i kursy",
"Kategorifilter på kategorisiden": "Filtr kategorii na stronie kategorii",
"Kilde (i)": "Źródło (i)",
"Kilde (k)": "Źródło (k)",
"Kladd": "Projekt",
"Klar til å melde deg på?": "Gotowy do rejestracji?",
"Klarte ikke å hente kursdager fra Kursagenten.": "Nie można pobrać dni kursu z Kursagenten.",
"Klasse": "Klasa",
"Klikk \"Lagre\" for å lagre navnendringen.": "Kliknij „Zapisz”, aby zapisać zmianę nazwy.",
"Klikk \"Lagre\".": "Kliknij „Zapisz”.",
"Klikk \"Legg til ny instruktør\".": "Kliknij „Dodaj nowego instruktora”.",
"Klikk for å kopiere": "Kliknij, aby skopiować",
"Klikk for å se de enkelte kursdagene med dato, klokkeslett, instruktør og lokale.": "Kliknij, aby wyświetlić poszczególne dni kursu z datą, godziną, instruktorem i salą.",
"Klikk på \"Egne innstillinger for instruktører\"": "Kliknij „Ustawienia niestandardowe dla instruktorów”",
"Klikk på \"Endre navn på nytt sted\" for å legge til en ny navnendring.": "Kliknij „Zmień nazwę dla nowej lokalizacji”, aby dodać nową zmianę nazwy.",
"Klikk på \"Legg til ny instruktør\".": "Kliknij „Dodaj nowego instruktora”.",
"Klikk på trekanten på menypunktet for å åpne innstillingene. Her kan du blant annet:": "Kliknij trójkąt na elemencie menu, aby otworzyć ustawienia. Tutaj możesz m.in.:",
"Klokkeslett": "Czas",
"Knappefarge tekst:": "Kolor tekstu przycisku:",
"Knappefarge:": "Kolor przycisku:",
"Knapper": "Pikolak",
"Kom i gang": "Zacznij",
"Kom i gang – A–Å": "Zacznij – A–Z",
"kommasepartert liste<br><strong>Standard</strong>: viser alle": "lista rozdzielana przecinkami<br><strong>Domyślna</strong>: pokazuje wszystko",
"Kompakt liste": "Lista kompaktowa",
"Konflikter funnet for skjulte URL-er:": "Znaleziono konflikty dla ukrytych adresów URL:",
"Kontakt": "Kontakt",
"Kontakt oss": "Skontaktuj się z nami",
"Kontaktinformasjon": "Informacje kontaktowe",
"Kopier kortkode for %s": "Skopiuj krótki kod dla %s",
"Kopier webhook-URL-en som vises på siden:": "Skopiuj adres URL webhooka widoczny na stronie:",
"Kort beskrivelse": "Krótki opis",
"Kort beskrivelse brukes i oversikter og som innledende tekst på detaljside": "Krótki opis jest używany w przeglądach i jako tekst wprowadzający na stronie szczegółów",
"Kort beskrivelse:": "Krótki opis:",
"kort<br><strong>Standard</strong>: ikke kort": "karta<br><strong>Domyślnie</strong>: nie karta",
"Kortkoder": "Krótkie kody",
"Kortkoder for lister og grid": "Shortcodes dla list i siatki",
"Kortkoder kan legges inn i teksten på sider og blogginnlegg. Du kan legge inn hele kurslisten, eller lister med enten alle kurskategorier, kurs i samme kategori (brukes på kurssider), eller instruktører.<br>Det er mange ulike valg. Du finner full kortkode under, med samtlige valg, samt en liste som forklarer alle valgene.<br>Kortkoden kopieres, og limes inn der du ønsker å vise den. <br>Merk at du må fjerne eventuelle valg du ikke trenger, og deler der flere valg er listet opp (feks som stablet/rad/liste).": "Shortcodes można wstawiać do treści strony i posta. Możesz wstawić pełną listę kursów lub listę wszystkich kategorii kursów, kursów w tej samej kategorii (używanej na stronach kursów) lub instruktorów.<br>Opcji jest wiele. Poniżej znajdziesz pełny krótki kod ze wszystkimi opcjami oraz listę wyjaśniającą każdą opcję.<br>Skopiuj krótki kod i wklej go w miejscu, w którym chcesz go wyświetlić.<br>Pamiętaj, że musisz usunąć opcje, których nie potrzebujesz, oraz części, w których wymienionych jest wiele opcji (np. stablet/rad/liste).",
"Kryss av for \"Aktiver regioninndeling\" for å aktivere funksjonen.": "Zaznacz opcję „Włącz podział regionalny”, aby włączyć tę funkcję.",
"Kryss av på \"Rydd opp i kurs\" om det er mange utløpte kursdatoer som vises på websiden. Det blir kjørt en nattlig opprydning, så det kan være unødvendig å gjøre dette nå. <strong>NB:</strong> Opprydding tar 3-5 minutter ekstra.": "Zaznacz opcję „Wyczyść kursy”, jeśli na stronie internetowej widocznych jest wiele nieaktualnych dat kursów. Co wieczór odbywa się sprzątanie, więc teraz może to być niepotrzebne. <strong>Uwaga:</strong> sprzątanie zajmuje dodatkowe 3–5 minut.",
"Kun for positiv filter (f.eks. nettbasert): skjuler stedsfilteret på kurslistesiden. Ved \"ikke-\"-filter vises filteret slik at bruker kan velge annet sted.": "Tylko dla filtra pozytywnego (np. online): ukrywa filtr lokalizacji na stronie z listą kursów. W przypadku filtra „nie-” jest on wyświetlany, dzięki czemu użytkownik może wybrać inną lokalizację.",
"Kunne ikke hente kursdager.": "Nie udało się pobrać dni kursów.",
"Kunne ikke hente oppdateringspakke: %s": "Nie można pobrać pakietu aktualizacji: %s",
"Kunne ikke laste filtrene. Vennligst prøv igjen.": "Nie udało się wczytać filtrów. Spróbuj ponownie.",
"Kunne ikke laste versjonshistorikk.": "Nie można wczytać historii wersji.",
"Kunne ikke skrive nedlastet pakke til midlertidig fil.": "Nie można zapisać pobranego pakietu do pliku tymczasowego.",
"Kunne ikke skrive XML-RPC-regel til .htaccess automatisk. Sjekk filrettigheter. Filen ligger vanligvis i WordPress-roten (samme nivå som wp-config.php). Kopier inn dette manuelt:<br><pre style=\"margin-top:8px;white-space:pre-wrap;\">%s</pre>": "Nie można automatycznie zapisać reguły XML-RPC w pliku .htaccess. Sprawdź uprawnienia do plików. Plik znajduje się zwykle w katalogu głównym WordPress (na tym samym poziomie co wp-config.php). Skopiuj to ręcznie:<br><pre style=\"margin-top:8px;white-space:pre-wrap;\">%s</pre>",
"Kurs": "Kurs",
"Kurs i samme kategori": "Kursy w tej samej kategorii",
"Kurs som er slettet i Kursagenten (finnes ikke lenger i API-et)": "Kursy usunięte w Kursagenten (nie są już w API)",
"Kursagenten admin": "Kursagenten administrator",
"Kursagenten automenyer": "Kursagenten menu automatyczne",
"Kursagenten legger til meta-tagger, Open Graph, Twitter Cards og Course-schema på kurs- og taksonomisider. Når du har en SEO-utvidelse installert, tilpasser vi oss automatisk for å unngå duplikater. <br>Du kan også skru av vår SEO helt hvis du bruker andre løsninger.": "Kursagenten dodaje metatagi, Open Graph, karty Twittera i schemat kursu na stronach kursów i taksonomii. Kiedy masz zainstalowaną wtyczkę SEO, dostosowujemy się automatycznie, aby uniknąć duplikatów. <br>Możesz także całkowicie wyłączyć nasz SEO, jeśli korzystasz z innych rozwiązań.",
"Kursagenten lisens": "Kursagenten licencja",
"Kursagenten plugin - Versjonshistorikk": "Wtyczka Kursagenten - Historia wersji",
"Kursagenten tilbyr både automenyer og meny-kortkoder, slik at du kan bygge dynamiske menyer som alltid speiler gjeldende kurskategorier, kurssteder og instruktører.": "Kursagenten oferuje zarówno menu automatyczne, jak i krótkie kody menu, dzięki czemu możesz tworzyć dynamiczne menu, które zawsze odzwierciedlają aktualne kategorie kursów, lokalizacje kursów i instruktorów.",
"Kursagenten: Denne lisensen er allerede i bruk på en annen side. Gi oss beskjed på post@kursagenten.no, så skal vi hjelpe deg. %sLegg inn ny lisens her%s.": "Kursagenten: Ta licencja jest już używana w innej witrynie. Skontaktuj się z nami pod adresem post@kursagenten.no, a my Ci pomożemy. %sWprowadź tutaj nową licencję%s.",
"Kursagenten: Lisensen er ugyldig eller slettet. %sLegg inn ny lisens her%s.": "Kursagenten: Licencja jest nieważna lub usunięta. %sWprowadź tutaj nową licencję%s.",
"Kursagenten: Lisensnøkkel lagret. Registrerer siden...": "Kursagenten: Klucz licencyjny został zapisany. Strona rejestracyjna...",
"Kursagenten: Lisensnøkkel mangler. %sLegg inn nøkkel her%s.": "Kursagenten: Brak klucza licencyjnego. %sWpisz klucz tutaj%s.",
"Kursagenten: Masserediger synlighet": "Kursagenten: Widoczność edycji zbiorczej",
"Kursagenten: Siden har blitt registrert hos oss, og kan nå brukes. Tilgjengelige oppdateringer vil bli gjort tilgjenglig i \"Utvidelser\".": "Kursagenten: Strona została u nas zarejestrowana i można z niej korzystać. Dostępne aktualizacje będą udostępniane w zakładce „Wtyczki”.",
"Kursdager:": "Dni kursu:",
"Kursdata fra Kursagenten": "Dane kursu z Kursagenten",
"Kursdato": "Data kursu",
"kursdato arkiv": "Archiwum dat kursów",
"Kursdato attributter": "Atrybuty daty kursu",
"Kursdato finnes ikke. coursedate_id må være WordPress post-ID for en ka_coursedate, ikke Kursagentens kurs-ID.": "Data kursu nie istnieje. Coursedate_id musi być identyfikatorem postu WordPress dla ka_coursedate, a nie identyfikatorem kursu Kursagenten.",
"Kursdato gjort om til kladd.": "Data kursu przywrócona do wersji roboczej.",
"Kursdato link": "Link do daty kursu",
"Kursdato liste": "Lista dat kursu",
"Kursdato listenavigasjon": "Nawigacja po liście dat kursów",
"Kursdato oppdatert.": "Data kursu zaktualizowana.",
"Kursdato planlagt.": "Termin kursu ustalony.",
"Kursdato publisert privat.": "Data kursu opublikowana prywatnie.",
"Kursdato publisert.": "Opublikowano datę kursu.",
"Kursdatoer": "Terminy kursów",
"Kursdatoer som er slettet eller utløpt": "Daty kursów, które zostały usunięte lub wygasły",
"Kursdatoer:": "Terminy kursów:",
"Kursdesign": "Projekt kursu",
"Kursene dine blir automatisk overført fra Kursagenten sammen med kurskategorier, kurssteder og instruktører. Men for å gi nettsiden din et profesjonelt uttrykk, kan du berike disse med bilder og tekst direkte på nettsiden.": "Twoje kursy zostaną automatycznie przeniesione z Kursagenten wraz z kategoriami kursów, lokalizacjami kursów i instruktorami. Aby jednak nadać swojej witrynie profesjonalny wygląd, możesz wzbogacić ją obrazami i tekstem bezpośrednio na stronie.",
"Kursene dine hentes fra Kursagenten på to måter:": "Twoje kursy są pobierane z Kursagenten na dwa sposoby:",
"Kurset er fullt": "Kurs jest pełny",
"Kurset er fullt. Du kan melde din interesse for å få mer informasjon eller å sette deg på venteliste.": "Kurs jest pełny. Możesz zarejestrować swoje zainteresowanie, aby uzyskać więcej informacji lub zapisać się na listę oczekujących.",
"Kurset varer fra %1$s til %2$s": "Kurs trwa od %1$s do %2$s",
"Kurset varer fra %s": "Kurs trwa od %s",
"Kursfilter": "Filtr kursu",
"Kursfilter på kategoriside": "Filtr kursu na stronie kategorii",
"Kursinformasjon": "Informacje o kursie",
"Kursinnstillinger": "Ustawienia kursu",
"Kurskategori": "Kategoria kursu",
"Kurskategori link": "Link do kategorii kursu",
"Kurskategorier kan berikes med bilder, ikoner og beskrivelser. Du kan også kontrollere hvor kategoriene vises.": "Kategorie kursów można wzbogacić o obrazy, ikony i opisy. Możesz także kontrolować, gdzie pojawiają się kategorie.",
"Kurskategorier liste": "Lista kategorii kursów",
"Kurskategorier listenavigasjon": "Nawigacja po liście kategorii kursów",
"Kurskategorier, automenyer": "Kategorie kursów, automatyczne menu",
"Kurskategorier, kurssteder og instruktører": "Kategorie kursów, lokalizacje kursów i instruktorzy",
"Kurskategorier, kurssteder og instruktører kan berikes med tekst og bilder om ønsket. Mer informasjon i seksjonen <a href=\"#berike-taksonomisider\">Berike taksonomisider</a>.": "Kategorie kursów, lokalizacje kursów i instruktorów można w razie potrzeby wzbogacić tekstem i obrazami. Więcej informacji w sekcji <a href=\"#berike-taksonomisider\">Wzbogacaj strony taksonomii</a>.",
"Kursliste": "Lista kursów",
"Kursliste etter": "Lista kursów po",
"Kursliste med filter": "Lista kursów z filtrem",
"Kursliste med filter <span class=\"small\"><a href=\"#lister\">mer info</a></span>": "Lista kursów z filtrem <span class=\"small\"><a href=\"#lister\">więcej informacji</a></span>",
"Kurslisten kan filtreres på kategori, sted, startmåned, språk m.m. Filtrene vises som del av kortkoden <code class=\"copytext\">[kursliste]</code>. Har du opprettet sider via <a href=\"admin.php?page=design\">Kursdesign</a> → Wordpress sider, gjelder dette siden \"Kurs\".": "Listę kursów można filtrować według kategorii, lokalizacji, miesiąca rozpoczęcia, języka itp. Filtry są częścią krótkiego kodu <code class=\"copytext\">[kursliste]</code>. Jeśli utworzyłeś strony poprzez strony <a href=\"admin.php?page=design\">Projekt kursu</a> → WordPress, dotyczy to strony „Kursy”.",
"Kurslokale": "Pokój kursowy",
"Kurslokale:": "Sala kursowa:",
"Kursoversikt": "Przegląd kursu",
"Kurspåmelding": "Rejestracja na kurs",
"Kurssted": "Lokalizacja kursu",
"Kurssted link": "Link do lokalizacji kursu",
"Kurssteder har samme synlighetsinnstillinger som kurskategorier (skjul i oversiktslister og i automenyer).": "Lokalizacje kursów mają takie same ustawienia widoczności jak kategorie kursów (ukryj je na listach przeglądowych i w menu automatycznym).",
"Kurssteder kan berikes med bilder og beskrivelser. Du kan også endre navn på steder og organisere dem i regioner.": "Lokalizacje kursów można wzbogacić o zdjęcia i opisy. Możesz także zmieniać nazwy lokalizacji i porządkować je w regionach.",
"Kurssteder liste": "Lista lokalizacji kursów",
"Kurssteder listenavigasjon": "Nawigacja po liście lokalizacji kursów",
"Kurssteder og regioner": "Lokalizacje i regiony kursów",
"Kurstider og steder": "Terminy i lokalizacje kursów",
"Kurstider:": "Godziny zajęć:",
"Lagre": "Zapisz",
"Lagre lisens": "Zapisz licencję",
"Lagre menyen som vanlig. På forsiden vil automenyen automatisk utvides til riktig trestruktur basert på taksonomier og kurs i Kursagenten.": "Zapisz menu jak zwykle. Na stronie głównej menu automatyczne zostanie automatycznie rozwinięte do prawidłowej struktury drzewa opartej na taksonomiach i kursach w Kursagenten.",
"Lagt inn direkte via WordPress": "Dodano bezpośrednio przez WordPress",
"Last opp %s": "Prześlij %s",
"Laster kursdager…": "Ładowanie dni kursu…",
"Lastet opp til dette kurset": "Przesłane do tego kursu",
"Lastet opp til kursdato": "Przesłano do daty kursu",
"Layout": "Układ",
"Layout:": "Układ:",
"Ledige kurs": "Dostępne kursy",
"Ledige kurs:": "Dostępne kursy:",
"Ledige plasser": "Dostępne miejsca",
"Legg automenyer under et hovedmenypunkt (f.eks. siden Kurs). Brukt som hovedmenypunkt vil toppnivået være uten link.": "Umieść menu automatyczne pod pozycją menu głównego (np. stroną Kursy). W przypadku użycia jako elementu menu głównego, najwyższy poziom nie będzie miał łącza.",
"Legg inn bedriftsinformasjon": "Wprowadź dane firmy",
"Legg inn betalingslenke %1$s i <a href=\"https://kursadmin.kursagenten.no/IframeSetting\" target=\"_blank\" rel=\"noopener\">Kursagenten</a>": "Dodaj link do płatności %1$s w <a href=\"https://kursadmin.kursagenten.no/IframeSetting\" target=\"_blank\" rel=\"noopener\">Kursagenten</a>",
"Legg inn innstillinger for å automatisk hente kurs fra Kursagenten. Når du har lagt inn innstillinger, kan du klikke på \"Hent alle kurs fra Kursagenten\" så blir alt hentet ved første gangs installering.": "Wprowadź ustawienia automatycznego pobierania kursów z Kursagenten. Po wprowadzeniu ustawień możesz kliknąć „Pobierz wszystkie kursy z Kursagenten”, aby pobrać wszystko przy pierwszej instalacji.",
"Legg inn kortkoden i tekstfeltet i en egendefinert meny. I url-feltet skriver du #. For å få menyen som en undermeny, dra dette menypunktet til høyre innunder et annet menypunkt. For å lage meny av en bestemt kategori (med underkategorier), skriv inn kategori-slug etter start=\"\".": "Wstaw krótki kod w polu tekstowym niestandardowego menu. W polu adresu URL wpisz #. Aby wyświetlić menu jako podmenu, przeciągnij ten element menu w prawo pod innym elementem menu. Aby utworzyć menu z określonej kategorii (z podkategoriami), wpisz informację o kategorii po start=\"\".",
"Legg inn lisensnøkkel": "Wprowadź klucz licencyjny",
"Legg til bilder og stedsbeskrivelser": "Dodaj zdjęcia i opisy lokalizacji",
"Legg til bilder, beskrivelser og organiser i hovedkategorier": "Dodawaj obrazy, opisy i organizuj je w główne kategorie",
"Legg til egendefinert CSS-klasse til wrapper-elementet. Nyttig for custom styling eller tema-spesifikke behov.": "Dodaj niestandardową klasę CSS do elementu opakowania. Przydatne w przypadku niestandardowych stylizacji lub potrzeb związanych z konkretnym motywem.",
"Legg til ekstra Wordpress innhold": "Dodaj dodatkową treść WordPress",
"Legg til i meny": "Dodaj do menu",
"Legg til instruktør": "Dodaj instruktora",
"Legg til KA kurs": "Dodaj kurs KA",
"Legg til kursdato": "Dodaj datę kursu",
"Legg til kurskategori": "Dodaj kategorię kursu",
"Legg til kurssted": "Dodaj lokalizację kursu",
"Legg til profilbilder og utvidet informasjon": "Dodaj zdjęcia profilowe i rozszerzone informacje",
"Legger automatisk inn og fjerner en blokkering av xmlrpc.php i .htaccess når valget skrus av/på. Krever Apache og skrivetilgang til .htaccess.<br><br>": "Automatycznie dodaje i usuwa blok xmlrpc.php w .htaccess, gdy opcja jest włączona/wyłączona. Wymaga Apache i dostępu do zapisu w .htaccess.<br><br>",
"Les mer": "Przeczytaj więcej",
"Like under hovedbilde/utvidet beskrivelse, før kurslisten.": "Tuż pod obrazem głównym/rozszerzonym opisem, przed listą kursów.",
"Lim inn lisensnøkkelen du fikk tildelt.": "Wklej przypisany klucz licencyjny.",
"Lim inn webhook-URL-en i feltene <strong>CourseCreated</strong> og <strong>CourseUpdated</strong>.": "Wklej adres URL webhooka w polach <strong>CourseCreated</strong> i <strong>CourseUpdated</strong>.",
"Link": "Połączyć",
"Link til en kursdato.": "Link do daty kursu.",
"Link til en kurskategori": "Link do kategorii kursu",
"Link til et instruktør": "Link do instruktora",
"Link til et kurssted": "Link do lokalizacji kursu",
"Link til kurs": "Link do kursu",
"Linker:": "Spinki do mankietów:",
"Lisensnøkkel": "Klucz licencyjny",
"List_type": "Typ_listy",
"Liste": "Lista",
"Listedesign:": "Projekt listy:",
"Listene med filtre i venstre kolonne kan bli lange. De begrenses til en standard høyde, med \"Vis mer\"-link. Standard høyde er 250px. Du kan velge en annen høyde for filterlister under.": "Listy filtrów w lewej kolumnie mogą być długie. Są ograniczone do domyślnej wysokości za pomocą linku „Pokaż więcej”. Domyślna wysokość to 250 pikseli. Poniżej możesz wybrać inną wysokość dla list filtrów.",
"Listetype": "Typ listy",
"Logg inn på <a href=\"https://kursadmin.kursagenten.no/IntegrationSettings\" target=\"_blank\">Kursagenten</a> og gå til <strong>Integrasjonsinnstillinger → Webhooks</strong>.": "Zaloguj się na <a href=\"https://kursadmin.kursagenten.no/IntegrationSettings\" target=\"_blank\">Kursagenten</a> i przejdź do <strong>Ustawienia integracji → Webhooks</strong>.",
"Lokale": "Pokój",
"Lokasjon:": "Lokalizacja:",
"lokasjoner oppdatert": "zaktualizowano lokalizacje",
"Lukk": "Zamknąć",
"Lukk filter": "Zamknij filtr",
"Lys tekst og mørkt overlay (standard)": "Jasny tekst i ciemna nakładka (domyślnie)",
"Maksbredde:": "Maksymalna szerokość:",
"Mangler Kursagenten-ID-er på kursdato.": "Brak identyfikatorów Kursagenten w dniu kursu.",
"Masseredigering av synlighet": "Widoczność edycji zbiorczej",
"Meld deg på": "Rejestr",
"Meld feil og forbedringer": "Zgłaszaj błędy i ulepszenia",
"Meld interesse": "Zarejestruj zainteresowanie",
"Meny-kortkoder": "Krótkie kody menu",
"Meny-kortkoder brukes når du vil bygge menyer ved hjelp av kortkoden <code class=\"copytext\">[ka-meny]</code>, typisk i en egendefinert meny eller i innhold der temaet støtter kortkoder.": "Krótkich kodów menu używa się, gdy chcesz tworzyć menu przy użyciu krótkiego kodu <code class=\"copytext\">[ka-meny]</code>, zazwyczaj w niestandardowym menu lub w treści, w której motyw obsługuje krótkie kody.",
"Menyer": "Menu",
"Mer info": "Więcej informacji",
"Mer informasjon": "Więcej informacji",
"Merk også \"Rydd opp i kurs\" før du kjører synken for å sikre at gamle kursdatoer fjernes.": "Przed uruchomieniem synchronizacji sprawdź także opcję „Wyczyść kursy”, aby upewnić się, że stare daty kursów zostały usunięte.",
"Merk: AIOSEO (Pro), SEOPress (Pro) og Slim SEO Schema (egen utvidelse) kan også sette opp eget Course-schema. Hvis du aktiverer dette i disse utvidelsene, anbefaler vi å skru av Kursagenten SEO for å unngå duplikater. For Rank Math Free anbefaler vi fortsatt Kursagenten sitt Course-schema som standard.": "Uwaga: AIOSEO (Pro), SEOPress (Pro) i Slim SEO Schema (oddzielne rozszerzenie) mogą również skonfigurować własny schemat kursu. Jeśli włączysz tę opcję w tych rozszerzeniach, zalecamy wyłączenie Kursagenten SEO, aby uniknąć duplikatów. W przypadku Rank Math Free nadal zalecamy domyślny schemat kursu Kursagenten.",
"Merk: instruktøren må være knyttet til et kurs for at dataene skal bli hentet over.": "Uwaga: aby dane mogły zostać pobrane, instruktor musi być powiązany z kursem.",
"Merk: på <a href=\"/wp-admin/admin.php?page=design#section-systemsider\">siden</a> med instruktøroversikten må du legge til vis=\"fornavn\" eller vis=\"etternavn\" i kortkoden for å vise kun fornavn eller etternavn. Du kan gå direkte til redigering fra <a href=\"/wp-admin/admin.php?page=design#section-systemsider\">Wordpress sider</a>.": "Uwaga: na <a href=\"/wp-admin/admin.php?page=design#section-systemsider\">stronie</a> z przeglądem instruktora musisz dodać vis=\"fornavn\" lub vis=\"etternavn\" do krótkiego kodu, aby wyświetlić tylko imię lub nazwisko. Możesz przejść bezpośrednio do edycji z <a href=\"/wp-admin/admin.php?page=design#section-systemsider\">WordPress stron</a>.",
"Mest brukt": "Najczęściej używany",
"Mobil:": "Przenośny:",
"Moderne": "Nowoczesny",
"Mørk tekst og lyst overlay": "Ciemny tekst i jasna nakładka",
"naviger i kurs": "Nawiguj po kursach",
"Navn": "Nazwa",
"Navn på nytt instruktør": "Imię i nazwisko nowego instruktora",
"Navn på nytt kurssted": "Nazwa nowej lokalizacji kursu",
"Navn på sted": "Nazwa lokalizacji",
"Navnendring": "Zmiana nazwy",
"Navnendring fjernet": "Usunięto zmianę nazwy",
"Navnendring ikke funnet": "Nie znaleziono zmiany nazwy",
"Navnendring lagret. Slug-oppdateringer vil skje ved neste synkronisering.": "Zmiana nazwy została zapisana. Aktualizacje ślimakowe pojawią się przy następnej synchronizacji.",
"Navnendring oppdatert. Slug-oppdateringer vil skje ved neste synkronisering.": "Zmiana nazwy została zaktualizowana. Aktualizacje ślimakowe pojawią się przy następnej synchronizacji.",
"Navnendring på kurssteder": "Zmiana nazw lokalizacji kursów",
"Navnet er det som vises på siden": "Nazwa jest tym, co jest wyświetlane na stronie",
"Navnet slik det som vises på siden. Bør kun endres på instruktørens brukerprofil på Kursagenten.": "Nazwa wyświetlana na stronie. Należy zmienić tylko w profilu użytkownika instruktora w Kursagenten.",
"Navnet slik det som vises på siden. Kan endres under <a href=\"%s\">Synkronisering</a>.": "Nazwa wyświetlana na stronie. Można to zmienić w sekcji <a href=\"%s\">Synchronizacja</a>.",
"Navnevisning:": "Wyświetlanie nazwy:",
"NB! Kjør full synk fra Kursagenten umiddelbart etter å ha lagt til/endret navn på et sted(er)!": "Uwaga! Uruchom pełną synchronizację z Kursagenten natychmiast po dodaniu/zmianie nazwy lokalizacji!",
"Nederst i høyre kolonne.": "Na dole prawej kolumny.",
"Nei": "NIE",
"Neste": "Następny",
"Neste 3 måneder": "Następne 3 miesiące",
"Neste 6 måneder": "Następne 6 miesięcy",
"Neste kurs": "Następny kurs",
"Neste kurs (fullt)": "Następny kurs (pełny)",
"Neste kurs:": "Następny kurs:",
"Neste uke": "Przyszły tydzień",
"Neste år": "Przyszły rok",
"Nettverksfeil. Prøv igjen.": "Błąd sieci. Spróbuj ponownie.",
"Nivå": "Poziom",
"Noe gikk galt ved kommunikasjon med serveren.": "Coś poszło nie tak podczas komunikacji z serwerem.",
"Noe gikk galt ved masseredigering.": "Coś poszło nie tak podczas edycji zbiorczej.",
"Normalt sett er disse områdene litt mørkere enn bakgrunnen. Brukes også som hovedfarge på bokser i \"Bokser\"-design.": "Zwykle te obszary są nieco ciemniejsze niż tło. Używany również jako kolor podstawowy na pudełkach w projekcie „Pudełko”.",
"Nullstill alle filtre": "Zresetuj wszystkie filtry",
"Nullstill dato": "Zresetuj datę",
"Nullstill filter": "Zresetuj filtry",
"Ny kursdato": "Nowy termin kursu",
"Nytt KA kurs": "Nowy kurs KA",
"Nytt navn for kurskategori": "Nowa nazwa kategorii kursu",
"Nytt navn på sted": "Nowa nazwa lokalizacji",
"Nyttige selectorer:": "Przydatne selektory:",
"Når aktivert, kan lokasjoner organiseres i regioner. Dette påvirker ikke synkronisering, men kan brukes for filtrering og organisering.": "Po włączeniu lokalizacje można organizować w regiony. Nie ma to wpływu na synchronizację, ale można go wykorzystać do filtrowania i porządkowania.",
"Når dette er aktivert vil kurslisten som standard skjule fulle kurs og kurs «på forespørsel». Brukeren kan slå filteret av igjen på siden.": "Gdy ta opcja jest włączona, lista kursów domyślnie ukrywa pełne kursy i kursy „na żądanie”. Użytkownik może ponownie wyłączyć filtr na stronie.",
"Når disse er aktive, slår vi av våre meta-tagger og overlater til utvidelsen. Course-schema leveres normalt av Kursagenten, med unntak av Rank Math Pro der vi lar Rank Math håndtere Course-schema.": "Gdy są one aktywne, wyłączamy nasze metatagi i pozostawiamy to wtyczce. Schemat kursu jest zwykle dostarczany przez Kursagenten, z wyjątkiem Rank Math Pro, w którym Rank Math obsługuje schemat kursu.",
"Når du besøker et kurs på frontend, finner du et redigeringsikon som tar deg direkte til kursredigering i Kursagenten. Dette gjør det enkelt å oppdatere kursinformasjon uten å gå veien om nettsiden.": "Gdy odwiedzisz kurs w interfejsie użytkownika, znajdziesz ikonę edycji, która przeniesie Cię bezpośrednio do edycji kursu w Kursagenten. Ułatwia to aktualizację informacji o kursie bez konieczności przeglądania strony internetowej.",
"Når du endrer navn på et sted:": "Gdy zmienisz nazwę lokalizacji:",
"Når webhooks er aktivert, vil kursene automatisk oppdateres i WordPress når de endres eller opprettes i Kursagenten. Dette gjelder både kursdata, datoer og lokasjoner.": "Gdy webhooki są włączone, kursy są automatycznie aktualizowane w WordPress, gdy zostaną zmienione lub utworzone w Kursagenten. Dotyczy to danych kursów, dat i lokalizacji.",
"Nåværende versjon:": "Aktualna wersja:",
"Om bedriften": "O firmie",
"Om firmaet": "O firmie",
"Om kurset": "O kursie",
"Om kursredigering": "Informacje o edycji kursu",
"Omdøp innlegg til Artikler": "Zmień nazwę postów na Artykuły",
"Oppdater instruktør": "Zaktualizuj instruktora",
"Oppdater kurskategori": "Zaktualizuj kategorię kursu",
"Oppdater kurssted": "Zaktualizuj lokalizację kursu",
"Oppførsel eksterne lenker:": "Zachowanie linku zewnętrznego:",
"Oppgi enten coursedate_id (WP post-ID) eller location_id + schedule_id (Kursagenten-IDer).": "Podaj identyfikator Coursedate_id (identyfikator wpisu WP) lub identyfikator lokalizacji + identyfikator harmonogramu (identyfikatory Kursagenten).",
"Opprett eller velg nødvendige sider for kurs, kurskategorier, kurssteder og instruktører. Velg design på kursliste, enkeltkurs, kategorier, steder og instruktører. Velg hovedfarger.": "Utwórz lub wybierz niezbędne strony dla kursów, kategorii kursów, lokalizacji kursów i instruktorów. Wybierz projekt listy kursów, pojedynczego kursu, kategorii, lokalizacji i instruktorów. Wybierz kolory podstawowe.",
"Opprett først en <strong>egendefinert meny</strong> eller et menypunkt av typen \"Egendefinert lenke\".": "Najpierw utwórz <strong>niestandardowe menu</strong> lub element menu typu „Niestandardowy link”.",
"Opprett ny side": "Utwórz nową stronę",
"Opprette egne instruktører": "Tworzenie niestandardowych instruktorów",
"Opprydding av kurs": "Sprzątanie kursu",
"Opprydding fjerner kurs og kursdatoer som ikke lenger finnes i Kursagenten, samt utløpte kursdatoer. Dette holder nettsiden ryddig og oppdatert.": "Czyszczenie usuwa kursy i daty kursów, które już nie istnieją w Kursagenten, a także daty kursów, które wygasły. Dzięki temu witryna internetowa jest uporządkowana i aktualna.",
"Overordnet instruktør": "Instruktor rodzic",
"Overordnet instruktør:": "Instruktor rodzic:",
"Overordnet KA kurs:": "Kurs KA dla rodziców:",
"Overordnet kurssted": "Miejsce kursu dla rodziców",
"Overordnet kurssted:": "Miejsce kursu dla rodziców:",
"Oversikt": "Przegląd",
"oversikten": "przegląd",
"Oversiktsside for alle instruktører": "Strona przeglądu dla wszystkich instruktorów",
"Oversiktsside for alle kurskategorier": "Strona przeglądu wszystkich kategorii kursów",
"Oversiktsside for alle kurssteder": "Strona przeglądu wszystkich lokalizacji kursów",
"Oversiktsside/kalender for alle kurs": "Strona przeglądowa/kalendarz dla wszystkich kursów",
"Oversiktssider med kortkoder": "Strony przeglądowe z krótkimi kodami",
"Overskrift": "Nagłówek",
"Overskrive data fra Kursagenten": "Zastąp dane z Kursagenten",
"Overstyr hvilke detaljer som vises i hvert kurs i <span class=\"copytext\">[kursliste]</span>. Uten prefiks settes kun oppgitte felter til synlig. Med <span class=\"copytext\">-</span>/<span class=\"copytext\">!</span> skjules felt, og med <span class=\"copytext\">+</span> vises felt uten å endre resten.": "Zastąp wyświetlanie szczegółów każdego kursu w <span class=\"copytext\">[kursliste]</span>. Bez prefiksu wyświetlane są tylko określone pola. W przypadku <span class=\"copytext\">-</span>/<span class=\"copytext\">!</span> pola są ukryte; z polami <span class=\"copytext\">+</span> są wyświetlane bez zmiany pozostałych.",
"Overstyr innstillinger for spesifikke taksonomier": "Zastąp ustawienia dla określonych taksonomii",
"Overstyr profil fra Kursagenten": "Zastąp profil z Kursagenten",
"Overstyr profilbilde": "Zastąp zdjęcie profilowe",
"Overstyr visning av bilder i <span class=\"copytext\">[kursliste]</span>.": "Zastąp wyświetlanie obrazu w <span class=\"copytext\">[kursliste]</span>.",
"Overstyr visning av filtre for <span class=\"copytext\">[kursliste]</span>. Nyttig når samme liste skal brukes i ulike sideoppsett.": "Zastąp wyświetlanie filtra dla <span class=\"copytext\">[kursliste]</span>. Przydatne, gdy ta sama lista jest używana w różnych układach strony.",
"Overstyrer tekstfargen fra overlay-valget over.": "Zastępuje kolor tekstu wybrany powyżej nakładki.",
"Plassholderbilde for sted": "Obraz zastępczy lokalizacji",
"Bildeformat": "Format obrazu",
"Bilder": "Obrazy",
"Bildeformer": "Kształty obrazu",
"Bildekvalitet": "Jakość obrazu",
"Bildestørrelse": "Rozmiar obrazu",
"Bruk card-design": "Użyj projektu karty",
"Brukes når Skygge/kantstil = Ingen, men bruk ramme.": "Używane, gdy styl cienia/obramowania = Brak, ale użyj obramowania.",
"Bunn": "Spód",
"BUNN": "SPÓD",
"Datakilde": "Źródło danych",
"Det er mulig å legge inn plassholderbilder under Admin → Kursagenten → Kursdesign.": "Możesz dodać obrazy zastępcze w obszarze Admin → Kursagenten → Projekt kursu.",
"Det meste av data skal styres fra Kursagenten. Det er enkelte deler vi ikke har felter for, og for disse delene kan du berike kategori/sted/instruktør direkte her på nettsiden via Admin → Kursagenten → Kurssteder/Instruktører/Kurssteder": "Większością danych należy zarządzać od Kursagenten. W przypadku kilku części nie mamy pól i dla nich możesz wzbogacić kategorię/lokalizację/instruktora bezpośrednio na stronie poprzez Administrator → Kursagenten → Lokalizacje kursów/Instruktorzy/Lokalizacja kursów.",
"Desktop": "Pulpit",
"Du kan laste opp bilder for hver kategori. Det er også mulig å laste opp et «profilbilde». Dette kan brukes i blokker/kortkoder, som et alternativ til hovedbildet. Har det ikke blitt lastet opp et kategoribilde, vil den prøve å bruke et bilde fra et tilknyttet kurs. Om dette ikke finnes, vil den bruke plassholderbilde.": "Możesz przesyłać obrazy dla każdej kategorii. Możesz także przesłać „obrazek profilowy”. Można tego używać w blokach/skrótach jako alternatywę dla głównego obrazu. Jeśli nie przesłano żadnego obrazu kategorii, spróbuje użyć obrazu z połączonego kursu. Jeśli żaden nie zostanie znaleziony, zostanie użyty obraz zastępczy.",
"Div": "Dział",
"Dobbel": "Podwójnie",
"Egendefinert": "Zwyczaj",
"Egendefinert format": "Niestandardowy format",
"Egendefinert størrelse (px)": "Rozmiar niestandardowy (px)",
"Eks: 5/4, 7/5": "Np. 5/4, 7/5",
"Ekstra fet": "Bardzo odważne",
"Ekstra kraftig": "Bardzo mocny",
"Ekstra stor": "Bardzo duży",
"Enkeltkurs": "Pojedynczy kurs",
"Element-justering": "Wyrównanie elementów",
"Element-justering %s": "Wyrównanie elementów %s",
"Element-kort": "Karta elementu",
"Etternavn": "Nazwisko",
"Fant ingen foreldrekategorier.": "Nie znaleziono kategorii nadrzędnych.",
"Fant ingen instruktører.": "Nie znaleziono instruktorów.",
"Fant ingen kurssteder.": "Nie znaleziono lokalizacji kursów.",
"Farge": "Kolor",
"Farger": "Zabarwienie",
"Fet": "Pogrubiony",
"Firkantet": "Kwadrat",
"Fontstørrelse for beskrivelse": "Rozmiar czcionki w opisie",
"Fontstørrelse for tittel": "Rozmiar czcionki tytułu",
"Fontvekt tekst": "Tekst o grubości czcionki",
"Fontvekt tittel": "Tytuł grubości czcionki",
"Foreldrekategori (valgfritt)": "Kategoria nadrzędna (opcjonalnie)",
"Fornavn": "Imię",
"Full størrelse": "Pełny rozmiar",
"Generelt": "Ogólny",
"God skikk for opplasting av bilder er å ha en maks størrelse på 500kb. I overføring fra Kursagenten er det en maksgrense for overføring på 1MB.": "Dobrą praktyką w zakresie przesyłania obrazów jest maksymalny rozmiar 500 KB. W przypadku transferu z Kursagenten maksymalny limit transferu wynosi 1 MB.",
"Halvfet": "Półpogrubione",
"Hovedbilde": "Główny obraz",
"Hovedkategorier": "Główne kategorie",
"Hover": "Wahać się",
"Høyre": "Prawidłowy",
"HØYRE": "PRAWIDŁOWY",
"I Kursagenten kan det legges inn bilder på hvert enkelt kurs. Om ikke bilde har blitt lastet opp, kan det brukes et plassholderbilde.": "Obrazy można dodawać do poszczególnych kursów w Kursagenten. Jeśli nie przesłano żadnego obrazu, można użyć obrazu zastępczego.",
"Ingen": "Nic",
"Ingen region": "Brak regionu",
"Ingen tilgjengelige valg.": "Brak dostępnych opcji.",
"Ingen, men bruk ramme": "Brak, ale użyj granicy",
"Instruktører": "Instruktorzy",
"Justeringer": "Korekty",
"Kantstil": "Styl graniczny",
"Kantlinjeradius": "Promień granicy",
"Kildetype": "Typ źródła",
"Kolonner": "Kolumny",
"Kort margin": "Margines karty",
"Kort padding": "Wypełnienie karty",
"Kraftig": "Mocny",
"Kursagenten Taxonomi": "Kursagenten Taksonomia",
"Kurskategorier": "Kategorie kursów",
"Kategorinavnet blir hentet fra taggene i Kursagenten. Disse kan du strukturere i ønsket hierarki her på nettsiden, i maks to nivåer. Hvis du ønsker å endre kategorinavnet, bør du endre taggen i Kursagenten. Merk: en ny kurskategori blir opprettet, men den gamle blir ikke slettet. Overfør eventuell tekst og bilder til den nye kategorien.": "Nazwa kategorii jest pobierana ze znaczników w Kursagenten. Można je uporządkować w dowolnej hierarchii na stronie internetowej, maksymalnie na dwóch poziomach. Jeśli chcesz zmienić nazwę kategorii, powinieneś zmienić tag w Kursagenten. Uwaga: zostanie utworzona nowa kategoria kursu, ale stara nie zostanie usunięta. Przenieś dowolny tekst i obrazy do nowej kategorii.",
"Kategoritekst: her har vi ingen felter i Kursagenten, og alt må legges inn på nettsiden. Du har mulighet til å legge inn både Kort beskrivelse og Lang beskrivelse. Dette dukker opp på de enkelte kurskategori-sidene på nettsiden.": "Tekst kategorii: nie mamy na to pól w Kursagenten i wszystko trzeba dodać na stronie. Możesz dodać zarówno krótki opis, jak i długi opis. Pojawiają się one na stronach poszczególnych kategorii kursów w witrynie internetowej.",
"Kurssteder": "Lokalizacje kursów",
"Kvadrat 1:1": "Kwadrat 1:1",
"Landskap 16:9": "Krajobraz 16:9",
"Landskap 2:1": "Krajobraz 2:1",
"Landskap 3:1": "Krajobraz 3:1",
"Landskap 3:2": "Krajobraz 3:2",
"Landskap 4:1": "Krajobraz 4:1",
"Landskap 4:3": "Krajobraz 4:3",
"Large": "Duży",
"Layout og stil": "Układ i styl",
"Liste enkel": "Prosta lista",
"Liten": "Mały",
"Maks ord i beskrivelse": "Maksymalna liczba słów w opisie",
"Maks ord i lang beskrivelse": "Maksymalna liczba słów w długim opisie",
"Medium": "Średni",
"Mer avrundet": "Bardziej zaokrąglone",
"mer informasjon": "więcej informacji",
"Mer informasjon om dataflyt fra Kursagenten": "Więcej informacji o przepływie danych z Kursagenten",
"Minste font (mobil) til største font (stor desktop). Gir en gradvis økning i fontstørrelse.": "Najmniejsza czcionka (mobilna) do największej czcionki (duży komputer stacjonarny). Zapewnia stopniowe zwiększanie rozmiaru czcionki.",
"Mobil": "Przenośny",
"Mørk overlay (%)": "Ciemna nakładka (%)",
"Nettbrett": "Tabletka",
"Normal": "Normalna",
"Navn, telefonnummer og epost blir overført fra Kursagenten. Dette kan overstyres på nettsiden om ønskelig.": "Imię i nazwisko, numer telefonu i adres e-mail zostały przeniesione z Kursagenten. W razie potrzeby można to zmienić na stronie internetowej.",
"Om du velger å vise bilde, vil det først bli sett etter hovedbilde fra kurssted. Hvis det ikke blir funnet, brukes plassholderbilde.": "Jeśli zdecydujesz się wyświetlić obraz, najpierw wyszukany zostanie główny obraz z lokalizacji kursu. Jeśli żaden nie zostanie znaleziony, zostanie użyty obraz zastępczy.",
"Standard": "Standard",
};
